# generated by datamodel-codegen:
#   filename:  workdir/arubacloud_crossplane_io_v1alpha1_vpntunnel.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProjectIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ProjectIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class IdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class IdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class PublicIp(BaseModel):
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    ID of the elastic public IP.
    """
    idRef: IdRef | None = None
    """
    Reference to a Elasticip in arubacloud to populate id.
    """
    idSelector: IdSelector | None = None
    """
    Selector for a Elasticip in arubacloud to populate id.
    """


class Subnet(BaseModel):
    cidr: str | None = None
    """
    (String) CIDR block of the subnet (e.g. 192.168.10.0/24). Required by the API.
    CIDR block of the subnet (e.g. `192.168.10.0/24`). Required by the API.
    """
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    ID of the subnet.
    """
    idRef: IdRef | None = None
    """
    Reference to a Subnet in arubacloud to populate id.
    """
    idSelector: IdSelector | None = None
    """
    Selector for a Subnet in arubacloud to populate id.
    """


class Vpc(BaseModel):
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    ID of the VPC.
    """
    idRef: IdRef | None = None
    """
    Reference to a VPC in arubacloud to populate id.
    """
    idSelector: IdSelector | None = None
    """
    Selector for a VPC in arubacloud to populate id.
    """


class IpConfigurations(BaseModel):
    publicIp: PublicIp | None = None
    """
    (Attributes) Reference to the elastic public IP assigned to this tunnel. (see below for nested schema)
    """
    subnet: Subnet | None = None
    """
    (Attributes) Reference to the subnet used by this tunnel. (see below for nested schema)
    """
    vpc: Vpc | None = None
    """
    (Attributes) Reference to the VPC this tunnel is attached to. (see below for nested schema)
    """


class Esp(BaseModel):
    encryption: str | None = None
    """
    (String) ESP encryption algorithm (e.g., aes256).
    ESP encryption algorithm (e.g., `aes256`).
    """
    hash: str | None = None
    """
    (String) ESP integrity/hash algorithm (e.g., sha256).
    ESP integrity/hash algorithm (e.g., `sha256`).
    """
    lifetime: float | None = None
    """
    2 lifetime in seconds.
    ESP phase-2 lifetime in seconds.
    """
    pfs: str | None = None
    """
    group<N>" (e.g. "dh-group14" for MODP-2048).
    ESP Perfect Forward Secrecy group. Use `"enable"`, `"disable"`, or `"dh-group<N>"` (e.g. `"dh-group14"` for MODP-2048).
    """


class Ike(BaseModel):
    dhGroup: str | None = None
    """
    Hellman group. Use the numeric group identifier: "1", "2", "5", "14" … "32". The common choice for IKEv2 is "14" (MODP-2048).
    IKE Diffie-Hellman group. Use the numeric group identifier: `"1"`, `"2"`, `"5"`, `"14"` … `"32"`. The common choice for IKEv2 is `"14"` (MODP-2048).
    """
    dpdAction: str | None = None
    """
    (String) Dead Peer Detection action on failure (e.g., restart).
    Dead Peer Detection action on failure (e.g., `restart`).
    """
    dpdInterval: float | None = None
    """
    alive interval in seconds.
    DPD keep-alive interval in seconds.
    """
    dpdTimeout: float | None = None
    """
    (Number) DPD timeout before the peer is considered dead, in seconds.
    DPD timeout before the peer is considered dead, in seconds.
    """
    encryption: str | None = None
    """
    (String) ESP encryption algorithm (e.g., aes256).
    IKE encryption algorithm (e.g., `aes256`).
    """
    hash: str | None = None
    """
    (String) ESP integrity/hash algorithm (e.g., sha256).
    IKE integrity/hash algorithm (e.g., `sha256`).
    """
    lifetime: float | None = None
    """
    2 lifetime in seconds.
    IKE phase-1 lifetime in seconds.
    """


class Psk(BaseModel):
    cloudSite: str | None = None
    """
    shared key itself goes into secret. Equivalent to leftid/rightid in strongSwan or the local/remote ID in a Fortinet phase-1 configuration.
    IKE identity of the ArubaCloud side of the tunnel ("PSK ID Aruba Side" in the control panel). This is an **identifier**, not a key — the pre-shared key itself goes into `secret`. Equivalent to `leftid`/`rightid` in strongSwan or the local/remote ID in a Fortinet phase-1 configuration.
    """
    onPremSite: str | None = None
    """
    premises side of the tunnel ("PSK ID On Prem Side" in the control panel). This is an identifier, not a key — the pre-shared key itself goes into secret. With some firewalls (e.g. Fortinet) this must be set to the public IP of the on-premises gateway.
    IKE identity of the on-premises side of the tunnel ("PSK ID On Prem Side" in the control panel). This is an **identifier**, not a key — the pre-shared key itself goes into `secret`. With some firewalls (e.g. Fortinet) this must be set to the public IP of the on-premises gateway.
    """
    secret: str | None = None
    """
    — sent to the API but not returned in read responses.
    Shared secret used to authenticate the VPN tunnel. Write-only — this value is sent to the API but is not returned in subsequent read responses.
    """


class VpnClientSettings(BaseModel):
    esp: Esp | None = None
    """
    2 settings. (see below for nested schema)
    """
    ike: Ike | None = None
    """
    1 settings. (see below for nested schema)
    """
    peerClientPublicIp: str | None = None
    """
    premises gateway).
    Public IP address of the remote peer (on-premises gateway).
    """
    psk: Psk | None = None
    """
    Shared Key (PSK) authentication settings. (see below for nested schema)
    """


class Properties(BaseModel):
    billingPeriod: str | None = None
    """
    (String) Billing cycle for the resource. Accepted values: Hour, Month, Year.
    Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
    """
    ipConfigurations: IpConfigurations | None = None
    """
    (Attributes) Network references for the VPN tunnel — VPC, subnet, and public IP. (see below for nested schema)
    """
    vpnClientProtocol: str | None = None
    """
    (String) IKE protocol version. Accepted values: ikev2.
    IKE protocol version. Accepted values: `ikev2`.
    """
    vpnClientSettings: VpnClientSettings | None = None
    """
    (Attributes) IKE/ESP/PSK client settings for the VPN tunnel. (see below for nested schema)
    """
    vpnType: str | None = None
    """
    To-Site.
    Type of VPN tunnel. Accepted values: `Site-To-Site`.
    """


class ForProvider(BaseModel):
    location: str | None = None
    """
    Bergamo). See the available locations and zones.
    Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
    """
    name: str | None = None
    """
    (String) Display name for the VPN tunnel.
    Display name for the VPN tunnel.
    """
    projectId: str | None = None
    """
    (String) ID of the project that owns this resource.
    ID of the project that owns this resource.
    """
    projectIdRef: ProjectIdRef | None = None
    """
    Reference to a Project in arubacloud to populate projectId.
    """
    projectIdSelector: ProjectIdSelector | None = None
    """
    Selector for a Project in arubacloud to populate projectId.
    """
    properties: Properties | None = None
    """
    (Attributes) Configuration properties for the VPN tunnel. (see below for nested schema)
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags attached to the resource for filtering and organisation.
    List of string tags attached to the resource for filtering and organisation.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """


class InitProvider(BaseModel):
    location: str | None = None
    """
    Bergamo). See the available locations and zones.
    Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
    """
    name: str | None = None
    """
    (String) Display name for the VPN tunnel.
    Display name for the VPN tunnel.
    """
    projectId: str | None = None
    """
    (String) ID of the project that owns this resource.
    ID of the project that owns this resource.
    """
    projectIdRef: ProjectIdRef | None = None
    """
    Reference to a Project in arubacloud to populate projectId.
    """
    projectIdSelector: ProjectIdSelector | None = None
    """
    Selector for a Project in arubacloud to populate projectId.
    """
    properties: Properties | None = None
    """
    (Attributes) Configuration properties for the VPN tunnel. (see below for nested schema)
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags attached to the resource for filtering and organisation.
    List of string tags attached to the resource for filtering and organisation.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class PublicIpModel(BaseModel):
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    ID of the elastic public IP.
    """


class SubnetModel(BaseModel):
    cidr: str | None = None
    """
    (String) CIDR block of the subnet (e.g. 192.168.10.0/24). Required by the API.
    CIDR block of the subnet (e.g. `192.168.10.0/24`). Required by the API.
    """
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    ID of the subnet.
    """


class VpcModel(BaseModel):
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    ID of the VPC.
    """


class AtProvider(BaseModel):
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    """
    location: str | None = None
    """
    Bergamo). See the available locations and zones.
    Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
    """
    name: str | None = None
    """
    (String) Display name for the VPN tunnel.
    Display name for the VPN tunnel.
    """
    projectId: str | None = None
    """
    (String) ID of the project that owns this resource.
    ID of the project that owns this resource.
    """
    properties: Properties | None = None
    """
    (Attributes) Configuration properties for the VPN tunnel. (see below for nested schema)
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags attached to the resource for filtering and organisation.
    List of string tags attached to the resource for filtering and organisation.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """
    uri: str | None = None
    """
    (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
    Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Vpntunnel(BaseModel):
    apiVersion: Literal['arubacloud.crossplane.io/v1alpha1'] | None = (
        'arubacloud.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Vpntunnel'] | None = 'Vpntunnel'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    VpntunnelSpec defines the desired state of Vpntunnel
    """
    status: Status | None = None
    """
    VpntunnelStatus defines the observed state of Vpntunnel.
    """


class VpntunnelList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Vpntunnel]
    """
    List of vpntunnels. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """