apiVersion: dev.crossplane.io/v1alpha1
kind: Project
metadata:
  name: containerday-2026
spec:
  dependencies:
  - type: xpkg
    xpkg:
      apiVersion: pkg.crossplane.io/v1
      kind: Provider
      package: xpkg.upbound.io/arubacloud/provider-arubacloud
      version: 'v0.0.10'
  - type: xpkg
    xpkg:
      apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: 'v0.2.1'
  - type: xpkg
    xpkg:
      apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: 'v0.8.0'
  - type: xpkg
    xpkg:
      apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.upbound.io/crossplane-contrib/function-extra-resources
      version: 'v0.3.0'
  repository: github.com/Arubacloud/containerday-2026
