# generated by datamodel-codegen:
#   filename:  workdir/arubacloud_crossplane_io_v1alpha1_securityrule.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProjectIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ProjectIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class Target(BaseModel):
    kind: str | None = None
    """
    insensitive — the value is normalised before sending to the API). (Immutable — changing this value forces the resource to be destroyed and re-created.)
    Type of the target endpoint. Accepted values: `IP`, `SecurityGroup` (case-insensitive — the value is normalised before sending to the API). (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    value: str | None = None
    """
    created.)
    Source (inbound) or destination (outbound) CIDR in notation like `0.0.0.0/0`, or SecurityGroup URI. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """


class Properties(BaseModel):
    direction: str | None = None
    """
    created.)
    Traffic direction the rule applies to. Accepted values: `Ingress`, `Egress`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    port: str | None = None
    """
    8090). Defaults to * (all ports) when omitted — the API normalises an omitted port to *, so the default keeps plan and state consistent. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    Port or port range for TCP/UDP (e.g., `80` or `8080-8090`). Defaults to `*` (all ports) when omitted — the API normalises an omitted port to `*`, so the default keeps plan and state consistent. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    protocol: str | None = None
    """
    insensitive — the value is normalised before sending to the API). (Immutable — changing this value forces the resource to be destroyed and re-created.)
    IP protocol. Accepted values: `TCP`, `UDP`, `ICMP`, `ANY` (case-insensitive — the value is normalised before sending to the API). (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    target: Target | None = None
    """
    created.) (see below for nested schema)
    """


class SecurityGroupIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SecurityGroupIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class VpcIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    location: str | None = None
    """
    Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    name: str | None = None
    """
    (String) Display name for the security rule.
    Display name for the security rule.
    """
    projectId: str | None = None
    """
    created.)
    ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    projectIdRef: ProjectIdRef | None = None
    """
    Reference to a Project in arubacloud to populate projectId.
    """
    projectIdSelector: ProjectIdSelector | None = None
    """
    Selector for a Project in arubacloud to populate projectId.
    """
    properties: Properties | None = None
    """
    matching properties of the security rule. All fields are immutable after creation — to change any of them, destroy and re-create the rule. (see below for nested schema)
    """
    securityGroupId: str | None = None
    """
    created.)
    ID of the security group this rule belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    securityGroupIdRef: SecurityGroupIdRef | None = None
    """
    Reference to a Securitygroup in arubacloud to populate securityGroupId.
    """
    securityGroupIdSelector: SecurityGroupIdSelector | None = None
    """
    Selector for a Securitygroup in arubacloud to populate securityGroupId.
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags attached to the resource for filtering and organisation.
    List of string tags attached to the resource for filtering and organisation.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """
    vpcId: str | None = None
    """
    created.)
    ID of the VPC this security rule belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in arubacloud to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in arubacloud to populate vpcId.
    """


class InitProvider(BaseModel):
    location: str | None = None
    """
    Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    name: str | None = None
    """
    (String) Display name for the security rule.
    Display name for the security rule.
    """
    projectId: str | None = None
    """
    created.)
    ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    projectIdRef: ProjectIdRef | None = None
    """
    Reference to a Project in arubacloud to populate projectId.
    """
    projectIdSelector: ProjectIdSelector | None = None
    """
    Selector for a Project in arubacloud to populate projectId.
    """
    properties: Properties | None = None
    """
    matching properties of the security rule. All fields are immutable after creation — to change any of them, destroy and re-create the rule. (see below for nested schema)
    """
    securityGroupId: str | None = None
    """
    created.)
    ID of the security group this rule belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    securityGroupIdRef: SecurityGroupIdRef | None = None
    """
    Reference to a Securitygroup in arubacloud to populate securityGroupId.
    """
    securityGroupIdSelector: SecurityGroupIdSelector | None = None
    """
    Selector for a Securitygroup in arubacloud to populate securityGroupId.
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags attached to the resource for filtering and organisation.
    List of string tags attached to the resource for filtering and organisation.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """
    vpcId: str | None = None
    """
    created.)
    ID of the VPC this security rule belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    vpcIdRef: VpcIdRef | None = None
    """
    Reference to a VPC in arubacloud to populate vpcId.
    """
    vpcIdSelector: VpcIdSelector | None = None
    """
    Selector for a VPC in arubacloud to populate vpcId.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    """
    location: str | None = None
    """
    Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    name: str | None = None
    """
    (String) Display name for the security rule.
    Display name for the security rule.
    """
    projectId: str | None = None
    """
    created.)
    ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    properties: Properties | None = None
    """
    matching properties of the security rule. All fields are immutable after creation — to change any of them, destroy and re-create the rule. (see below for nested schema)
    """
    securityGroupId: str | None = None
    """
    created.)
    ID of the security group this rule belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags attached to the resource for filtering and organisation.
    List of string tags attached to the resource for filtering and organisation.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """
    uri: str | None = None
    """
    (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
    Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
    """
    vpcId: str | None = None
    """
    created.)
    ID of the VPC this security rule belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Securityrule(BaseModel):
    apiVersion: Literal['arubacloud.crossplane.io/v1alpha1'] | None = (
        'arubacloud.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Securityrule'] | None = 'Securityrule'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    SecurityruleSpec defines the desired state of Securityrule
    """
    status: Status | None = None
    """
    SecurityruleStatus defines the observed state of Securityrule.
    """


class SecurityruleList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Securityrule]
    """
    List of securityrules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """