# generated by datamodel-codegen:
#   filename:  workdir/pt_fn_crossplane_io_v1beta1_resources.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class String(BaseModel):
    fmt: str
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """


class Variable(BaseModel):
    fromFieldPath: str
    """
    FromFieldPath is the path of the field on the source whose value is
    to be used as input.
    """


class Combine(BaseModel):
    strategy: Literal['string'] = 'string'
    """
    Strategy defines the strategy to use to combine the input variable values.
    Currently only string is supported.
    """
    string: String | None = None
    """
    String declares that input variables should be combined into a single
    string, using the relevant settings for formatting purposes.
    """
    variables: list[Variable] = Field(..., min_length=1)
    """
    Variables are the list of variables whose values will be retrieved and
    combined.
    """


class Policy(BaseModel):
    fromFieldPath: Literal['Optional', 'Required'] | None = None
    """
    FromFieldPath specifies how to patch from a field path. The default is
    'Optional', which means the patch will be a no-op if the specified
    fromFieldPath does not exist. Use 'Required' to prevent the creation of a
    new composed resource until the required path exists.
    """
    toFieldPath: (
        Literal[
            'Replace',
            'MergeObjects',
            'MergeObjectsAppendArrays',
            'ForceMergeObjects',
            'ForceMergeObjectsAppendArrays',
            'MergeObject',
            'AppendArray',
        ]
        | None
    ) = None
    """
    ToFieldPath specifies how to patch to a field path. The default is
    'Replace', which means the patch will completely replace the target field,
    or create it if it does not exist. Use 'MergeObjects' to recursively merge the patch
    object with the target object, while keeping target object keys, but overwriting any array values, or use
    'MergeObjectsAppendArrays' to recursively merge the patch object with the target object, while keeping
    target object keys and appending any array values to target array values, or use
    'ForceMergeObjects' to recursively merge the patch object with the target object, overwriting
    any target object keys, including array values, or use
    'ForceMergeObjectsAppendArrays' to recursively merge the patch object with the target object,
    overwriting target object keys, and appending any array values to target array values.
    'MergeObject' is deprecated, use 'MergeObjects' instead, which is functionally identical.
    'AppendArray' is deprecated, use 'ForceMergeObjectsAppendArrays' instead, which is functionally identical.
    """


class Convert(BaseModel):
    format: Literal['none', 'quantity', 'json'] | None = None
    """
    The expected input format.

    * `quantity` - parses the input as a K8s [`resource.Quantity`](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#Quantity).
    Only used during `string -> float64` conversions.
    * `json` - parses the input as a JSON string.
    Only used during `string -> object` or `string -> list` conversions.

    If this property is null, the default conversion is applied.
    """
    toType: Literal['string', 'int', 'int64', 'bool', 'float64', 'object', 'array']
    """
    ToType is the type of the output of this transform.
    """


class Pattern(BaseModel):
    literal: str | None = None
    """
    Literal exactly matches the input string (case sensitive).
    Is required if `type` is `literal`.
    """
    regexp: str | None = None
    """
    Regexp to match against the input string.
    Is required if `type` is `regexp`.
    """
    result: Any
    """
    The value that is used as result of the transform if the pattern matches.
    """
    type: Literal['literal', 'regexp']
    """
    Type specifies how the pattern matches the input.

    * `literal` - the pattern value has to exactly match (case sensitive) the
    input string. This is the default.

    * `regexp` - the pattern treated as a regular expression against
    which the input string is tested. Crossplane will throw an error if the
    key is not a valid regexp.
    """


class Match(BaseModel):
    fallbackTo: Literal['Value', 'Input'] | None = 'Value'
    """
    Determines to what value the transform should fallback if no pattern matches.
    """
    fallbackValue: Any | None = None
    """
    The fallback value that should be returned by the transform if now pattern
    matches.
    """
    patterns: list[Pattern] | None = None
    """
    The patterns that should be tested against the input string.
    Patterns are tested in order. The value of the first match is used as
    result of this transform.
    """


class Math(BaseModel):
    clampMax: int | None = None
    """
    ClampMax makes sure that the value is not bigger than the given value.
    """
    clampMin: int | None = None
    """
    ClampMin makes sure that the value is not smaller than the given value.
    """
    multiply: int | None = None
    """
    Multiply the value.
    """
    type: Literal['Multiply', 'ClampMin', 'ClampMax'] | None = 'Multiply'
    """
    Type of the math transform to be run.
    """


class Join(BaseModel):
    separator: str
    """
    Separator to join the input strings.
    """


class Regexp(BaseModel):
    group: int | None = None
    """
    Group number to match. 0 (the default) matches the entire expression.
    """
    match: str
    """
    Match string. May optionally include submatches, aka capture groups.
    See https://pkg.go.dev/regexp/ for details.
    """


class Replace(BaseModel):
    replace: str
    """
    The Replace string replaces all occurrences of the search string.
    """
    search: str
    """
    The Search string to match.
    """


class StringModel(BaseModel):
    convert: (
        Literal[
            'ToUpper',
            'ToLower',
            'ToBase64',
            'FromBase64',
            'ToJson',
            'ToSha1',
            'ToSha256',
            'ToSha512',
        ]
        | None
    ) = None
    """
    Optional conversion method to be specified.
    `ToUpper` and `ToLower` change the letter case of the input string.
    `ToBase64` and `FromBase64` perform a base64 conversion based on the input string.
    `ToJson` converts any input value into its raw JSON representation.
    `ToSha1`, `ToSha256` and `ToSha512` generate a hash value based on the input
    converted to JSON.
    """
    fmt: str | None = None
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """
    join: Join | None = None
    """
    Join the input strings.
    """
    regexp: Regexp | None = None
    """
    Extract a match from the input using a regular expression.
    """
    replace: Replace | None = None
    """
    Search/Replace applied to the input string.
    """
    trim: str | None = None
    """
    Trim the prefix or suffix from the input
    """
    type: Literal['Format', 'Convert', 'TrimPrefix', 'TrimSuffix', 'Regexp']
    """
    Type of the string transform to be run.
    """


class Transform(BaseModel):
    convert: Convert | None = None
    """
    Convert is used to cast the input into the given output type.
    """
    map: dict[str, Any] | None = None
    """
    Map uses the input as a key in the given map and returns the value.
    """
    match: Match | None = None
    """
    Match is a more complex version of Map that matches a list of patterns.
    """
    math: Math | None = None
    """
    Math is used to transform the input via mathematical operations such as
    multiplication.
    """
    string: StringModel | None = None
    """
    String is used to transform the input into a string or a different kind
    of string. Note that the input does not necessarily need to be a string.
    """
    type: Literal['map', 'match', 'math', 'string', 'convert']
    """
    Type of the transform to be run.
    """


class Patch(BaseModel):
    combine: Combine | None = None
    """
    Combine is the patch configuration for a CombineFromComposite,
    CombineToComposite patch.
    """
    fromFieldPath: str | None = None
    """
    FromFieldPath is the path of the field on the resource whose value is
    to be used as input. Required when type is FromCompositeFieldPath or
    ToCompositeFieldPath.
    """
    policy: Policy | None = None
    """
    Policy configures the specifics of patching behaviour.
    """
    toFieldPath: str | None = None
    """
    ToFieldPath is the path of the field on the resource whose value will
    be changed with the result of transforms. Leave empty if you'd like to
    propagate to the same path as fromFieldPath.
    """
    transforms: list[Transform] | None = None
    """
    Transforms are the list of functions that are used as a FIFO pipe for the
    input to be transformed.
    """
    type: (
        Literal[
            'FromCompositeFieldPath',
            'ToCompositeFieldPath',
            'CombineFromComposite',
            'CombineToComposite',
            'FromEnvironmentFieldPath',
            'ToEnvironmentFieldPath',
        ]
        | None
    ) = 'FromCompositeFieldPath'
    """
    Type sets the patching behaviour to be used. Each patch type may require
    its own fields to be set on the Patch object.
    """


class Environment(BaseModel):
    patches: list[Patch] | None = None
    """
    Patches is a list of environment patches that are executed before a
    composition's resources are composed. These patches are between the XR
    and the Environment. Either from the Environment to the XR, or vice
    versa.
    """


class StringModel1(BaseModel):
    fmt: str
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """


class StringModel2(BaseModel):
    convert: (
        Literal[
            'ToUpper',
            'ToLower',
            'ToBase64',
            'FromBase64',
            'ToJson',
            'ToSha1',
            'ToSha256',
            'ToSha512',
        ]
        | None
    ) = None
    """
    Optional conversion method to be specified.
    `ToUpper` and `ToLower` change the letter case of the input string.
    `ToBase64` and `FromBase64` perform a base64 conversion based on the input string.
    `ToJson` converts any input value into its raw JSON representation.
    `ToSha1`, `ToSha256` and `ToSha512` generate a hash value based on the input
    converted to JSON.
    """
    fmt: str | None = None
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """
    join: Join | None = None
    """
    Join the input strings.
    """
    regexp: Regexp | None = None
    """
    Extract a match from the input using a regular expression.
    """
    replace: Replace | None = None
    """
    Search/Replace applied to the input string.
    """
    trim: str | None = None
    """
    Trim the prefix or suffix from the input
    """
    type: Literal['Format', 'Convert', 'TrimPrefix', 'TrimSuffix', 'Regexp']
    """
    Type of the string transform to be run.
    """


class PatchModel(BaseModel):
    combine: Combine | None = None
    """
    Combine is the patch configuration for a CombineFromComposite,
    CombineToComposite patch.
    """
    fromFieldPath: str | None = None
    """
    FromFieldPath is the path of the field on the resource whose value is
    to be used as input. Required when type is FromCompositeFieldPath or
    ToCompositeFieldPath.
    """
    policy: Policy | None = None
    """
    Policy configures the specifics of patching behaviour.
    """
    toFieldPath: str | None = None
    """
    ToFieldPath is the path of the field on the resource whose value will
    be changed with the result of transforms. Leave empty if you'd like to
    propagate to the same path as fromFieldPath.
    """
    transforms: list[Transform] | None = None
    """
    Transforms are the list of functions that are used as a FIFO pipe for the
    input to be transformed.
    """
    type: (
        Literal[
            'FromCompositeFieldPath',
            'ToCompositeFieldPath',
            'CombineFromComposite',
            'CombineToComposite',
            'FromEnvironmentFieldPath',
            'ToEnvironmentFieldPath',
            'CombineFromEnvironment',
            'CombineToEnvironment',
        ]
        | None
    ) = 'FromCompositeFieldPath'
    """
    Type sets the patching behaviour to be used. Each patch type may require
    its own fields to be set on the ComposedPatch object.
    """


class PatchSet(BaseModel):
    name: str
    """
    Name of this PatchSet.
    """
    patches: list[PatchModel]
    """
    Patches will be applied as an overlay to the base resource.
    """


class ConnectionDetail(BaseModel):
    fromConnectionSecretKey: str | None = None
    """
    FromConnectionSecretKey is the key that will be used to fetch the value
    from the composed resource's connection secret.
    """
    fromFieldPath: str | None = None
    """
    FromFieldPath is the path of the field on the composed resource whose
    value to be used as input. Name must be specified if the type is
    FromFieldPath.
    """
    name: str
    """
    Name of the connection secret key that will be propagated to the
    connection secret of the composed resource.
    """
    type: Literal['FromConnectionSecretKey', 'FromFieldPath', 'FromValue']
    """
    Type sets the connection detail fetching behavior to be used. Each
    connection detail type may require its own fields to be set on the
    ConnectionDetail object.
    """
    value: str | None = None
    """
    Value that will be propagated to the connection secret of the composite
    resource. May be set to inject a fixed, non-sensitive connection secret
    value, for example a well-known port.
    """


class StringModel3(BaseModel):
    fmt: str
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """


class StringModel4(BaseModel):
    convert: (
        Literal[
            'ToUpper',
            'ToLower',
            'ToBase64',
            'FromBase64',
            'ToJson',
            'ToSha1',
            'ToSha256',
            'ToSha512',
        ]
        | None
    ) = None
    """
    Optional conversion method to be specified.
    `ToUpper` and `ToLower` change the letter case of the input string.
    `ToBase64` and `FromBase64` perform a base64 conversion based on the input string.
    `ToJson` converts any input value into its raw JSON representation.
    `ToSha1`, `ToSha256` and `ToSha512` generate a hash value based on the input
    converted to JSON.
    """
    fmt: str | None = None
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """
    join: Join | None = None
    """
    Join the input strings.
    """
    regexp: Regexp | None = None
    """
    Extract a match from the input using a regular expression.
    """
    replace: Replace | None = None
    """
    Search/Replace applied to the input string.
    """
    trim: str | None = None
    """
    Trim the prefix or suffix from the input
    """
    type: Literal['Format', 'Convert', 'TrimPrefix', 'TrimSuffix', 'Regexp']
    """
    Type of the string transform to be run.
    """


class PatchModel1(BaseModel):
    combine: Combine | None = None
    """
    Combine is the patch configuration for a CombineFromComposite,
    CombineToComposite patch.
    """
    fromFieldPath: str | None = None
    """
    FromFieldPath is the path of the field on the resource whose value is
    to be used as input. Required when type is FromCompositeFieldPath or
    ToCompositeFieldPath.
    """
    patchSetName: str | None = None
    """
    PatchSetName to include patches from. Required when type is PatchSet.
    """
    policy: Policy | None = None
    """
    Policy configures the specifics of patching behaviour.
    """
    toFieldPath: str | None = None
    """
    ToFieldPath is the path of the field on the resource whose value will
    be changed with the result of transforms. Leave empty if you'd like to
    propagate to the same path as fromFieldPath.
    """
    transforms: list[Transform] | None = None
    """
    Transforms are the list of functions that are used as a FIFO pipe for the
    input to be transformed.
    """
    type: (
        Literal[
            'FromCompositeFieldPath',
            'PatchSet',
            'ToCompositeFieldPath',
            'CombineFromComposite',
            'CombineToComposite',
            'FromEnvironmentFieldPath',
            'ToEnvironmentFieldPath',
            'CombineFromEnvironment',
            'CombineToEnvironment',
        ]
        | None
    ) = 'FromCompositeFieldPath'
    """
    Type sets the patching behaviour to be used. Each patch type may require
    its own fields to be set on the ComposedPatch object.
    """


class MatchCondition(BaseModel):
    status: str
    """
    Status is the status of the condition you'd like to match.
    """
    type: str
    """
    Type indicates the type of condition you'd like to use.
    """


class ReadinessCheck(BaseModel):
    fieldPath: str | None = None
    """
    FieldPath shows the path of the field whose value will be used.
    """
    matchCondition: MatchCondition | None = None
    """
    MatchCondition specifies the condition you'd like to match if you're using "MatchCondition" type.
    """
    matchInteger: int | None = None
    """
    MatchInt is the value you'd like to match if you're using "MatchInt" type.
    """
    matchString: str | None = None
    """
    MatchString is the value you'd like to match if you're using "MatchString" type.
    """
    type: Literal[
        'MatchString',
        'MatchInteger',
        'NonEmpty',
        'MatchCondition',
        'MatchTrue',
        'MatchFalse',
        'None',
    ]
    """
    Type indicates the type of probe you'd like to use.
    """


class Resource(BaseModel):
    base: dict[str, Any] | None = None
    """
    Base of the composed resource that patches will be applied to and from.
    If base is omitted, a previous Function within the pipeline must have
    produced the named composed resource. Patches will be applied to and from
    that resource. If base is specified, and a previous Function within the
    pipeline produced the name composed resource, it will be overwritten.
    """
    connectionDetails: list[ConnectionDetail] | None = None
    """
    ConnectionDetails lists the propagation secret keys from this composed
    resource to the composition instance connection secret.
    """
    name: str
    """
    A Name uniquely identifies this entry within its resources array.
    """
    patches: list[PatchModel1] | None = None
    """
    Patches to and from the composed resource.
    """
    readinessChecks: list[ReadinessCheck] | None = Field(
        [
            {
                'matchCondition': {'status': 'True', 'type': 'Ready'},
                'type': 'MatchCondition',
            }
        ],
        validate_default=True,
    )
    """
    ReadinessChecks allows users to define custom readiness checks. All
    checks have to return true in order for resource to be considered ready.
    The default readiness check is to have the "Ready" condition to be
    "True".
    """


class StringModel5(BaseModel):
    fmt: str
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """


class StringModel6(BaseModel):
    convert: (
        Literal[
            'ToUpper',
            'ToLower',
            'ToBase64',
            'FromBase64',
            'ToJson',
            'ToSha1',
            'ToSha256',
            'ToSha512',
        ]
        | None
    ) = None
    """
    Optional conversion method to be specified.
    `ToUpper` and `ToLower` change the letter case of the input string.
    `ToBase64` and `FromBase64` perform a base64 conversion based on the input string.
    `ToJson` converts any input value into its raw JSON representation.
    `ToSha1`, `ToSha256` and `ToSha512` generate a hash value based on the input
    converted to JSON.
    """
    fmt: str | None = None
    """
    Format the input using a Go format string. See
    https://golang.org/pkg/fmt/ for details.
    """
    join: Join | None = None
    """
    Join the input strings.
    """
    regexp: Regexp | None = None
    """
    Extract a match from the input using a regular expression.
    """
    replace: Replace | None = None
    """
    Search/Replace applied to the input string.
    """
    trim: str | None = None
    """
    Trim the prefix or suffix from the input
    """
    type: Literal['Format', 'Convert', 'TrimPrefix', 'TrimSuffix', 'Regexp']
    """
    Type of the string transform to be run.
    """


class PatchModel2(BaseModel):
    combine: Combine | None = None
    """
    Combine is the patch configuration for a CombineFromComposite,
    CombineToComposite patch.
    """
    fromFieldPath: str | None = None
    """
    FromFieldPath is the path of the field on the resource whose value is
    to be used as input. Required when type is FromCompositeFieldPath or
    ToCompositeFieldPath.
    """
    policy: Policy | None = None
    """
    Policy configures the specifics of patching behaviour.
    """
    toFieldPath: str | None = None
    """
    ToFieldPath is the path of the field on the resource whose value will
    be changed with the result of transforms. Leave empty if you'd like to
    propagate to the same path as fromFieldPath.
    """
    transforms: list[Transform] | None = None
    """
    Transforms are the list of functions that are used as a FIFO pipe for the
    input to be transformed.
    """
    type: Literal['FromCompositeFieldPath', 'CombineFromComposite'] | None = (
        'FromCompositeFieldPath'
    )
    """
    Type sets the patch type. Only FromCompositeFieldPath and CombineFromComposite
    are supported for connection secret patches.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str | None = None
    """
    Name of the connection secret. If not specified, defaults to {xr-name}-connection.
    """
    namespace: str | None = None
    """
    Namespace of the connection secret. If not specified for namespaced XRs,
    Crossplane will default it to the XR's namespace. For cluster-scoped XRs,
    namespace must be explicitly provided.
    """
    patches: list[PatchModel2] | None = None
    """
    Patches define transformations to apply to the connection secret reference.
    Patches are only applied from the composite resource to the secret reference.
    Supported patch types: FromCompositeFieldPath, CombineFromComposite.
    ToFieldPath must be either "name" or "namespace".
    """


class Resources(BaseModel):
    apiVersion: Literal['pt.fn.crossplane.io/v1beta1'] | None = (
        'pt.fn.crossplane.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    environment: Environment | None = None
    """
    Environment represents the Composition environment.

    THIS IS AN ALPHA FIELD.
    Do not use it in production. It may be changed or removed without notice.
    """
    kind: Literal['Resources'] | None = 'Resources'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    patchSets: list[PatchSet] | None = None
    """
    PatchSets define a named set of patches that may be included by any
    resource. PatchSets cannot themselves refer to other PatchSets.
    """
    resources: list[Resource]
    """
    Resources is a list of resource templates that will be used when a
    composite resource is created.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToRef specifies the name and namespace of a Secret
    to which any connection details for this composite resource should be
    written. This field is only used for Crossplane v2 composite resources.
    For v1 composite resources, connection details are returned via the
    RunFunctionResponse and handled by Crossplane core.
    """


class ResourcesList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Resources]
    """
    List of resources. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """