// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BackupAPIVersion.
const (
	BackupAPIVersionArubacloudCrossplaneIoV1Alpha1 BackupAPIVersion = "arubacloud.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the BackupAPIVersion enum.
func (e BackupAPIVersion) Valid() bool {
	switch e {
	case BackupAPIVersionArubacloudCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for BackupKind.
const (
	BackupKindBackup BackupKind = "Backup"
)

// Valid indicates whether the value is a known member of the BackupKind enum.
func (e BackupKind) Valid() bool {
	switch e {
	case BackupKindBackup:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderProjectIDRefPolicyResolution.
const (
	BackupSpecForProviderProjectIDRefPolicyResolutionOptional BackupSpecForProviderProjectIDRefPolicyResolution = "Optional"
	BackupSpecForProviderProjectIDRefPolicyResolutionRequired BackupSpecForProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderProjectIDRefPolicyResolution enum.
func (e BackupSpecForProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecForProviderProjectIDRefPolicyResolutionOptional:
		return true
	case BackupSpecForProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderProjectIDRefPolicyResolve.
const (
	BackupSpecForProviderProjectIDRefPolicyResolveAlways       BackupSpecForProviderProjectIDRefPolicyResolve = "Always"
	BackupSpecForProviderProjectIDRefPolicyResolveIfNotPresent BackupSpecForProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderProjectIDRefPolicyResolve enum.
func (e BackupSpecForProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecForProviderProjectIDRefPolicyResolveAlways:
		return true
	case BackupSpecForProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderProjectIDSelectorPolicyResolution.
const (
	BackupSpecForProviderProjectIDSelectorPolicyResolutionOptional BackupSpecForProviderProjectIDSelectorPolicyResolution = "Optional"
	BackupSpecForProviderProjectIDSelectorPolicyResolutionRequired BackupSpecForProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderProjectIDSelectorPolicyResolution enum.
func (e BackupSpecForProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecForProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case BackupSpecForProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderProjectIDSelectorPolicyResolve.
const (
	BackupSpecForProviderProjectIDSelectorPolicyResolveAlways       BackupSpecForProviderProjectIDSelectorPolicyResolve = "Always"
	BackupSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent BackupSpecForProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderProjectIDSelectorPolicyResolve enum.
func (e BackupSpecForProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecForProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case BackupSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderVolumeIDRefPolicyResolution.
const (
	BackupSpecForProviderVolumeIDRefPolicyResolutionOptional BackupSpecForProviderVolumeIDRefPolicyResolution = "Optional"
	BackupSpecForProviderVolumeIDRefPolicyResolutionRequired BackupSpecForProviderVolumeIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderVolumeIDRefPolicyResolution enum.
func (e BackupSpecForProviderVolumeIDRefPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecForProviderVolumeIDRefPolicyResolutionOptional:
		return true
	case BackupSpecForProviderVolumeIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderVolumeIDRefPolicyResolve.
const (
	BackupSpecForProviderVolumeIDRefPolicyResolveAlways       BackupSpecForProviderVolumeIDRefPolicyResolve = "Always"
	BackupSpecForProviderVolumeIDRefPolicyResolveIfNotPresent BackupSpecForProviderVolumeIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderVolumeIDRefPolicyResolve enum.
func (e BackupSpecForProviderVolumeIDRefPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecForProviderVolumeIDRefPolicyResolveAlways:
		return true
	case BackupSpecForProviderVolumeIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderVolumeIDSelectorPolicyResolution.
const (
	BackupSpecForProviderVolumeIDSelectorPolicyResolutionOptional BackupSpecForProviderVolumeIDSelectorPolicyResolution = "Optional"
	BackupSpecForProviderVolumeIDSelectorPolicyResolutionRequired BackupSpecForProviderVolumeIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderVolumeIDSelectorPolicyResolution enum.
func (e BackupSpecForProviderVolumeIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecForProviderVolumeIDSelectorPolicyResolutionOptional:
		return true
	case BackupSpecForProviderVolumeIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecForProviderVolumeIDSelectorPolicyResolve.
const (
	BackupSpecForProviderVolumeIDSelectorPolicyResolveAlways       BackupSpecForProviderVolumeIDSelectorPolicyResolve = "Always"
	BackupSpecForProviderVolumeIDSelectorPolicyResolveIfNotPresent BackupSpecForProviderVolumeIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecForProviderVolumeIDSelectorPolicyResolve enum.
func (e BackupSpecForProviderVolumeIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecForProviderVolumeIDSelectorPolicyResolveAlways:
		return true
	case BackupSpecForProviderVolumeIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderProjectIDRefPolicyResolution.
const (
	BackupSpecInitProviderProjectIDRefPolicyResolutionOptional BackupSpecInitProviderProjectIDRefPolicyResolution = "Optional"
	BackupSpecInitProviderProjectIDRefPolicyResolutionRequired BackupSpecInitProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderProjectIDRefPolicyResolution enum.
func (e BackupSpecInitProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecInitProviderProjectIDRefPolicyResolutionOptional:
		return true
	case BackupSpecInitProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderProjectIDRefPolicyResolve.
const (
	BackupSpecInitProviderProjectIDRefPolicyResolveAlways       BackupSpecInitProviderProjectIDRefPolicyResolve = "Always"
	BackupSpecInitProviderProjectIDRefPolicyResolveIfNotPresent BackupSpecInitProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderProjectIDRefPolicyResolve enum.
func (e BackupSpecInitProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecInitProviderProjectIDRefPolicyResolveAlways:
		return true
	case BackupSpecInitProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderProjectIDSelectorPolicyResolution.
const (
	BackupSpecInitProviderProjectIDSelectorPolicyResolutionOptional BackupSpecInitProviderProjectIDSelectorPolicyResolution = "Optional"
	BackupSpecInitProviderProjectIDSelectorPolicyResolutionRequired BackupSpecInitProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderProjectIDSelectorPolicyResolution enum.
func (e BackupSpecInitProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecInitProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case BackupSpecInitProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderProjectIDSelectorPolicyResolve.
const (
	BackupSpecInitProviderProjectIDSelectorPolicyResolveAlways       BackupSpecInitProviderProjectIDSelectorPolicyResolve = "Always"
	BackupSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent BackupSpecInitProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderProjectIDSelectorPolicyResolve enum.
func (e BackupSpecInitProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecInitProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case BackupSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderVolumeIDRefPolicyResolution.
const (
	BackupSpecInitProviderVolumeIDRefPolicyResolutionOptional BackupSpecInitProviderVolumeIDRefPolicyResolution = "Optional"
	BackupSpecInitProviderVolumeIDRefPolicyResolutionRequired BackupSpecInitProviderVolumeIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderVolumeIDRefPolicyResolution enum.
func (e BackupSpecInitProviderVolumeIDRefPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecInitProviderVolumeIDRefPolicyResolutionOptional:
		return true
	case BackupSpecInitProviderVolumeIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderVolumeIDRefPolicyResolve.
const (
	BackupSpecInitProviderVolumeIDRefPolicyResolveAlways       BackupSpecInitProviderVolumeIDRefPolicyResolve = "Always"
	BackupSpecInitProviderVolumeIDRefPolicyResolveIfNotPresent BackupSpecInitProviderVolumeIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderVolumeIDRefPolicyResolve enum.
func (e BackupSpecInitProviderVolumeIDRefPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecInitProviderVolumeIDRefPolicyResolveAlways:
		return true
	case BackupSpecInitProviderVolumeIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderVolumeIDSelectorPolicyResolution.
const (
	BackupSpecInitProviderVolumeIDSelectorPolicyResolutionOptional BackupSpecInitProviderVolumeIDSelectorPolicyResolution = "Optional"
	BackupSpecInitProviderVolumeIDSelectorPolicyResolutionRequired BackupSpecInitProviderVolumeIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderVolumeIDSelectorPolicyResolution enum.
func (e BackupSpecInitProviderVolumeIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BackupSpecInitProviderVolumeIDSelectorPolicyResolutionOptional:
		return true
	case BackupSpecInitProviderVolumeIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecInitProviderVolumeIDSelectorPolicyResolve.
const (
	BackupSpecInitProviderVolumeIDSelectorPolicyResolveAlways       BackupSpecInitProviderVolumeIDSelectorPolicyResolve = "Always"
	BackupSpecInitProviderVolumeIDSelectorPolicyResolveIfNotPresent BackupSpecInitProviderVolumeIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackupSpecInitProviderVolumeIDSelectorPolicyResolve enum.
func (e BackupSpecInitProviderVolumeIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BackupSpecInitProviderVolumeIDSelectorPolicyResolveAlways:
		return true
	case BackupSpecInitProviderVolumeIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackupSpecManagementPoliciesItem.
const (
	BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItem               BackupSpecManagementPoliciesItem = "*"
	BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemCreate         BackupSpecManagementPoliciesItem = "Create"
	BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemDelete         BackupSpecManagementPoliciesItem = "Delete"
	BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemLateInitialize BackupSpecManagementPoliciesItem = "LateInitialize"
	BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemObserve        BackupSpecManagementPoliciesItem = "Observe"
	BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemUpdate         BackupSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BackupSpecManagementPoliciesItem enum.
func (e BackupSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItem:
		return true
	case BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemCreate:
		return true
	case BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemDelete:
		return true
	case BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemLateInitialize:
		return true
	case BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemObserve:
		return true
	case BackupSpecManagementPoliciesItemBackupSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoCrossplaneArubacloudV1Alpha1Backup Backup is the Schema for the Backups API. Manages an ArubaCloud Block Storage Backup.
type IoCrossplaneArubacloudV1Alpha1Backup = Backup

// BackupAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BackupAPIVersion string

// BackupKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BackupKind string

// BackupSpecForProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecForProviderProjectIDRefPolicyResolution string

// BackupSpecForProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecForProviderProjectIDRefPolicyResolve string

// BackupSpecForProviderProjectIDRefPolicy Policies for referencing.
type BackupSpecForProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecForProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecForProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecForProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type BackupSpecForProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BackupSpecForProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// BackupSpecForProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecForProviderProjectIDSelectorPolicyResolution string

// BackupSpecForProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecForProviderProjectIDSelectorPolicyResolve string

// BackupSpecForProviderProjectIDSelectorPolicy Policies for selection.
type BackupSpecForProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecForProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecForProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecForProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type BackupSpecForProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BackupSpecForProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// BackupSpecForProviderVolumeIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecForProviderVolumeIDRefPolicyResolution string

// BackupSpecForProviderVolumeIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecForProviderVolumeIDRefPolicyResolve string

// BackupSpecForProviderVolumeIDRefPolicy Policies for referencing.
type BackupSpecForProviderVolumeIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecForProviderVolumeIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecForProviderVolumeIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecForProviderVolumeIDRef Reference to a Blockstorage in arubacloud to populate volumeId.
type BackupSpecForProviderVolumeIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BackupSpecForProviderVolumeIDRefPolicy `json:"policy,omitempty"`
}

// BackupSpecForProviderVolumeIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecForProviderVolumeIDSelectorPolicyResolution string

// BackupSpecForProviderVolumeIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecForProviderVolumeIDSelectorPolicyResolve string

// BackupSpecForProviderVolumeIDSelectorPolicy Policies for selection.
type BackupSpecForProviderVolumeIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecForProviderVolumeIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecForProviderVolumeIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecForProviderVolumeIDSelector Selector for a Blockstorage in arubacloud to populate volumeId.
type BackupSpecForProviderVolumeIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BackupSpecForProviderVolumeIDSelectorPolicy `json:"policy,omitempty"`
}

// BackupSpecForProvider defines model for .
type BackupSpecForProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the backup.
	// Display name for the backup.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *BackupSpecForProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *BackupSpecForProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// RetentionDays created, because the API does not apply retention_days changes in update requests.)
	// Number of days to retain the backup before automatic deletion. Optional — if omitted, the backup is retained indefinitely. (Immutable — changing this value forces the resource to be destroyed and re-created, because the API does not apply retention_days changes in update requests.)
	RetentionDays *float32 `json:"retentionDays,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// Type created.)
	// Backup type. Accepted values: `Full`, `Incremental`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty"`

	// VolumeID created.)
	// ID of the block storage volume to back up. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	VolumeID *string `json:"volumeId,omitempty"`

	// VolumeIDRef Reference to a Blockstorage in arubacloud to populate volumeId.
	VolumeIDRef *BackupSpecForProviderVolumeIDRef `json:"volumeIdRef,omitempty"`

	// VolumeIDSelector Selector for a Blockstorage in arubacloud to populate volumeId.
	VolumeIDSelector *BackupSpecForProviderVolumeIDSelector `json:"volumeIdSelector,omitempty"`
}

// BackupSpecInitProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecInitProviderProjectIDRefPolicyResolution string

// BackupSpecInitProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecInitProviderProjectIDRefPolicyResolve string

// BackupSpecInitProviderProjectIDRefPolicy Policies for referencing.
type BackupSpecInitProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecInitProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecInitProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecInitProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type BackupSpecInitProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BackupSpecInitProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// BackupSpecInitProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecInitProviderProjectIDSelectorPolicyResolution string

// BackupSpecInitProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecInitProviderProjectIDSelectorPolicyResolve string

// BackupSpecInitProviderProjectIDSelectorPolicy Policies for selection.
type BackupSpecInitProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecInitProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecInitProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecInitProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type BackupSpecInitProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BackupSpecInitProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// BackupSpecInitProviderVolumeIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecInitProviderVolumeIDRefPolicyResolution string

// BackupSpecInitProviderVolumeIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecInitProviderVolumeIDRefPolicyResolve string

// BackupSpecInitProviderVolumeIDRefPolicy Policies for referencing.
type BackupSpecInitProviderVolumeIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecInitProviderVolumeIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecInitProviderVolumeIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecInitProviderVolumeIDRef Reference to a Blockstorage in arubacloud to populate volumeId.
type BackupSpecInitProviderVolumeIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BackupSpecInitProviderVolumeIDRefPolicy `json:"policy,omitempty"`
}

// BackupSpecInitProviderVolumeIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackupSpecInitProviderVolumeIDSelectorPolicyResolution string

// BackupSpecInitProviderVolumeIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackupSpecInitProviderVolumeIDSelectorPolicyResolve string

// BackupSpecInitProviderVolumeIDSelectorPolicy Policies for selection.
type BackupSpecInitProviderVolumeIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackupSpecInitProviderVolumeIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackupSpecInitProviderVolumeIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BackupSpecInitProviderVolumeIDSelector Selector for a Blockstorage in arubacloud to populate volumeId.
type BackupSpecInitProviderVolumeIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BackupSpecInitProviderVolumeIDSelectorPolicy `json:"policy,omitempty"`
}

// BackupSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BackupSpecInitProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the backup.
	// Display name for the backup.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *BackupSpecInitProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *BackupSpecInitProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// RetentionDays created, because the API does not apply retention_days changes in update requests.)
	// Number of days to retain the backup before automatic deletion. Optional — if omitted, the backup is retained indefinitely. (Immutable — changing this value forces the resource to be destroyed and re-created, because the API does not apply retention_days changes in update requests.)
	RetentionDays *float32 `json:"retentionDays,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// Type created.)
	// Backup type. Accepted values: `Full`, `Incremental`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty"`

	// VolumeID created.)
	// ID of the block storage volume to back up. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	VolumeID *string `json:"volumeId,omitempty"`

	// VolumeIDRef Reference to a Blockstorage in arubacloud to populate volumeId.
	VolumeIDRef *BackupSpecInitProviderVolumeIDRef `json:"volumeIdRef,omitempty"`

	// VolumeIDSelector Selector for a Blockstorage in arubacloud to populate volumeId.
	VolumeIDSelector *BackupSpecInitProviderVolumeIDSelector `json:"volumeIdSelector,omitempty"`
}

// BackupSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BackupSpecManagementPoliciesItem string

// BackupSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BackupSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// BackupSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BackupSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// BackupSpec BackupSpec defines the desired state of Backup
type BackupSpec struct {
	ForProvider *BackupSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BackupSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BackupSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BackupSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BackupSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BackupStatusAtProvider defines model for .
type BackupStatusAtProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// ID (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the backup.
	// Display name for the backup.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// RetentionDays created, because the API does not apply retention_days changes in update requests.)
	// Number of days to retain the backup before automatic deletion. Optional — if omitted, the backup is retained indefinitely. (Immutable — changing this value forces the resource to be destroyed and re-created, because the API does not apply retention_days changes in update requests.)
	RetentionDays *float32 `json:"retentionDays,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// Type created.)
	// Backup type. Accepted values: `Full`, `Incremental`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty"`

	// URI (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty"`

	// VolumeID created.)
	// ID of the block storage volume to back up. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	VolumeID *string `json:"volumeId,omitempty"`
}

// BackupStatusConditionsItem A Condition that may apply to a resource.
type BackupStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BackupStatus BackupStatus defines the observed state of Backup.
type BackupStatus struct {
	AtProvider *BackupStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BackupStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Backup Backup is the Schema for the Backups API. Manages an ArubaCloud Block Storage Backup.
type Backup struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BackupAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BackupKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BackupSpec defines the desired state of Backup
	Spec *BackupSpec `json:"spec,omitempty"`

	// Status BackupStatus defines the observed state of Backup.
	Status *BackupStatus `json:"status,omitempty"`
}

// IoCrossplaneArubacloudV1Alpha1BackupList BackupList is a list of Backup
type IoCrossplaneArubacloudV1Alpha1BackupList = BackupList

// BackupList BackupList is a list of Backup
type BackupList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of backups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneArubacloudV1Alpha1Backup `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
