// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BlockstorageAPIVersion.
const (
	BlockstorageAPIVersionArubacloudCrossplaneIoV1Alpha1 BlockstorageAPIVersion = "arubacloud.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the BlockstorageAPIVersion enum.
func (e BlockstorageAPIVersion) Valid() bool {
	switch e {
	case BlockstorageAPIVersionArubacloudCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageKind.
const (
	BlockstorageKindBlockstorage BlockstorageKind = "Blockstorage"
)

// Valid indicates whether the value is a known member of the BlockstorageKind enum.
func (e BlockstorageKind) Valid() bool {
	switch e {
	case BlockstorageKindBlockstorage:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecForProviderProjectIDRefPolicyResolution.
const (
	BlockstorageSpecForProviderProjectIDRefPolicyResolutionOptional BlockstorageSpecForProviderProjectIDRefPolicyResolution = "Optional"
	BlockstorageSpecForProviderProjectIDRefPolicyResolutionRequired BlockstorageSpecForProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecForProviderProjectIDRefPolicyResolution enum.
func (e BlockstorageSpecForProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case BlockstorageSpecForProviderProjectIDRefPolicyResolutionOptional:
		return true
	case BlockstorageSpecForProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecForProviderProjectIDRefPolicyResolve.
const (
	BlockstorageSpecForProviderProjectIDRefPolicyResolveAlways       BlockstorageSpecForProviderProjectIDRefPolicyResolve = "Always"
	BlockstorageSpecForProviderProjectIDRefPolicyResolveIfNotPresent BlockstorageSpecForProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecForProviderProjectIDRefPolicyResolve enum.
func (e BlockstorageSpecForProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case BlockstorageSpecForProviderProjectIDRefPolicyResolveAlways:
		return true
	case BlockstorageSpecForProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecForProviderProjectIDSelectorPolicyResolution.
const (
	BlockstorageSpecForProviderProjectIDSelectorPolicyResolutionOptional BlockstorageSpecForProviderProjectIDSelectorPolicyResolution = "Optional"
	BlockstorageSpecForProviderProjectIDSelectorPolicyResolutionRequired BlockstorageSpecForProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecForProviderProjectIDSelectorPolicyResolution enum.
func (e BlockstorageSpecForProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BlockstorageSpecForProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case BlockstorageSpecForProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecForProviderProjectIDSelectorPolicyResolve.
const (
	BlockstorageSpecForProviderProjectIDSelectorPolicyResolveAlways       BlockstorageSpecForProviderProjectIDSelectorPolicyResolve = "Always"
	BlockstorageSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent BlockstorageSpecForProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecForProviderProjectIDSelectorPolicyResolve enum.
func (e BlockstorageSpecForProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BlockstorageSpecForProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case BlockstorageSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecInitProviderProjectIDRefPolicyResolution.
const (
	BlockstorageSpecInitProviderProjectIDRefPolicyResolutionOptional BlockstorageSpecInitProviderProjectIDRefPolicyResolution = "Optional"
	BlockstorageSpecInitProviderProjectIDRefPolicyResolutionRequired BlockstorageSpecInitProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecInitProviderProjectIDRefPolicyResolution enum.
func (e BlockstorageSpecInitProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case BlockstorageSpecInitProviderProjectIDRefPolicyResolutionOptional:
		return true
	case BlockstorageSpecInitProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecInitProviderProjectIDRefPolicyResolve.
const (
	BlockstorageSpecInitProviderProjectIDRefPolicyResolveAlways       BlockstorageSpecInitProviderProjectIDRefPolicyResolve = "Always"
	BlockstorageSpecInitProviderProjectIDRefPolicyResolveIfNotPresent BlockstorageSpecInitProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecInitProviderProjectIDRefPolicyResolve enum.
func (e BlockstorageSpecInitProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case BlockstorageSpecInitProviderProjectIDRefPolicyResolveAlways:
		return true
	case BlockstorageSpecInitProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution.
const (
	BlockstorageSpecInitProviderProjectIDSelectorPolicyResolutionOptional BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution = "Optional"
	BlockstorageSpecInitProviderProjectIDSelectorPolicyResolutionRequired BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution enum.
func (e BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BlockstorageSpecInitProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case BlockstorageSpecInitProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve.
const (
	BlockstorageSpecInitProviderProjectIDSelectorPolicyResolveAlways       BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve = "Always"
	BlockstorageSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve enum.
func (e BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BlockstorageSpecInitProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case BlockstorageSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BlockstorageSpecManagementPoliciesItem.
const (
	BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItem               BlockstorageSpecManagementPoliciesItem = "*"
	BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemCreate         BlockstorageSpecManagementPoliciesItem = "Create"
	BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemDelete         BlockstorageSpecManagementPoliciesItem = "Delete"
	BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemLateInitialize BlockstorageSpecManagementPoliciesItem = "LateInitialize"
	BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemObserve        BlockstorageSpecManagementPoliciesItem = "Observe"
	BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemUpdate         BlockstorageSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BlockstorageSpecManagementPoliciesItem enum.
func (e BlockstorageSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItem:
		return true
	case BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemCreate:
		return true
	case BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemDelete:
		return true
	case BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemLateInitialize:
		return true
	case BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemObserve:
		return true
	case BlockstorageSpecManagementPoliciesItemBlockstorageSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoCrossplaneArubacloudV1Alpha1Blockstorage Blockstorage is the Schema for the Blockstorages API. Manages an ArubaCloud Block Storage volume.
type IoCrossplaneArubacloudV1Alpha1Blockstorage = Blockstorage

// BlockstorageAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BlockstorageAPIVersion string

// BlockstorageKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BlockstorageKind string

// BlockstorageSpecForProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BlockstorageSpecForProviderProjectIDRefPolicyResolution string

// BlockstorageSpecForProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BlockstorageSpecForProviderProjectIDRefPolicyResolve string

// BlockstorageSpecForProviderProjectIDRefPolicy Policies for referencing.
type BlockstorageSpecForProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BlockstorageSpecForProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BlockstorageSpecForProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BlockstorageSpecForProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type BlockstorageSpecForProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BlockstorageSpecForProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// BlockstorageSpecForProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BlockstorageSpecForProviderProjectIDSelectorPolicyResolution string

// BlockstorageSpecForProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BlockstorageSpecForProviderProjectIDSelectorPolicyResolve string

// BlockstorageSpecForProviderProjectIDSelectorPolicy Policies for selection.
type BlockstorageSpecForProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BlockstorageSpecForProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BlockstorageSpecForProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BlockstorageSpecForProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type BlockstorageSpecForProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BlockstorageSpecForProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// BlockstorageSpecForProvider defines model for .
type BlockstorageSpecForProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// Bootable (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	Bootable *bool `json:"bootable,omitempty"`

	// Image (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	Image *string `json:"image,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *BlockstorageSpecForProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *BlockstorageSpecForProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// SizeGb created, because the API rejects a smaller size (Validation: Size: invalid). A replacement discards the volume's contents — check the plan before applying.
	// Size of the block storage volume in GiB. Must be a positive integer. Growing a volume is applied in place; **shrinking forces the volume to be destroyed and re-created**, because the API rejects a smaller size (`Validation: Size: invalid`). A replacement discards the volume's contents — check the plan before applying.
	SizeGb *float32 `json:"sizeGb,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// Type created.)
	// Storage type. Accepted values: `Standard`, `Performance`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty"`

	// Zone (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	Zone *string `json:"zone,omitempty"`
}

// BlockstorageSpecInitProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BlockstorageSpecInitProviderProjectIDRefPolicyResolution string

// BlockstorageSpecInitProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BlockstorageSpecInitProviderProjectIDRefPolicyResolve string

// BlockstorageSpecInitProviderProjectIDRefPolicy Policies for referencing.
type BlockstorageSpecInitProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BlockstorageSpecInitProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BlockstorageSpecInitProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BlockstorageSpecInitProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type BlockstorageSpecInitProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BlockstorageSpecInitProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution string

// BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve string

// BlockstorageSpecInitProviderProjectIDSelectorPolicy Policies for selection.
type BlockstorageSpecInitProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BlockstorageSpecInitProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BlockstorageSpecInitProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BlockstorageSpecInitProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type BlockstorageSpecInitProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BlockstorageSpecInitProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// BlockstorageSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BlockstorageSpecInitProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// Bootable (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	Bootable *bool `json:"bootable,omitempty"`

	// Image (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	Image *string `json:"image,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *BlockstorageSpecInitProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *BlockstorageSpecInitProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// SizeGb created, because the API rejects a smaller size (Validation: Size: invalid). A replacement discards the volume's contents — check the plan before applying.
	// Size of the block storage volume in GiB. Must be a positive integer. Growing a volume is applied in place; **shrinking forces the volume to be destroyed and re-created**, because the API rejects a smaller size (`Validation: Size: invalid`). A replacement discards the volume's contents — check the plan before applying.
	SizeGb *float32 `json:"sizeGb,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// Type created.)
	// Storage type. Accepted values: `Standard`, `Performance`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty"`

	// Zone (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	Zone *string `json:"zone,omitempty"`
}

// BlockstorageSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BlockstorageSpecManagementPoliciesItem string

// BlockstorageSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BlockstorageSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// BlockstorageSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BlockstorageSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// BlockstorageSpec BlockstorageSpec defines the desired state of Blockstorage
type BlockstorageSpec struct {
	ForProvider *BlockstorageSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BlockstorageSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BlockstorageSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BlockstorageSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BlockstorageSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BlockstorageStatusAtProvider defines model for .
type BlockstorageStatusAtProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// Bootable (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	Bootable *bool `json:"bootable,omitempty"`

	// ID (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty"`

	// Image (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	Image *string `json:"image,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// SizeGb created, because the API rejects a smaller size (Validation: Size: invalid). A replacement discards the volume's contents — check the plan before applying.
	// Size of the block storage volume in GiB. Must be a positive integer. Growing a volume is applied in place; **shrinking forces the volume to be destroyed and re-created**, because the API rejects a smaller size (`Validation: Size: invalid`). A replacement discards the volume's contents — check the plan before applying.
	SizeGb *float32 `json:"sizeGb,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// Type created.)
	// Storage type. Accepted values: `Standard`, `Performance`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty"`

	// URI (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty"`

	// Zone (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	Zone *string `json:"zone,omitempty"`
}

// BlockstorageStatusConditionsItem A Condition that may apply to a resource.
type BlockstorageStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BlockstorageStatus BlockstorageStatus defines the observed state of Blockstorage.
type BlockstorageStatus struct {
	AtProvider *BlockstorageStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BlockstorageStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Blockstorage Blockstorage is the Schema for the Blockstorages API. Manages an ArubaCloud Block Storage volume.
type Blockstorage struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BlockstorageAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BlockstorageKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BlockstorageSpec defines the desired state of Blockstorage
	Spec *BlockstorageSpec `json:"spec,omitempty"`

	// Status BlockstorageStatus defines the observed state of Blockstorage.
	Status *BlockstorageStatus `json:"status,omitempty"`
}

// IoCrossplaneArubacloudV1Alpha1BlockstorageList BlockstorageList is a list of Blockstorage
type IoCrossplaneArubacloudV1Alpha1BlockstorageList = BlockstorageList

// BlockstorageList BlockstorageList is a list of Blockstorage
type BlockstorageList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of blockstorages. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneArubacloudV1Alpha1Blockstorage `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
