// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for KeypairAPIVersion.
const (
	KeypairAPIVersionArubacloudCrossplaneIoV1Alpha1 KeypairAPIVersion = "arubacloud.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the KeypairAPIVersion enum.
func (e KeypairAPIVersion) Valid() bool {
	switch e {
	case KeypairAPIVersionArubacloudCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for KeypairKind.
const (
	KeypairKindKeypair KeypairKind = "Keypair"
)

// Valid indicates whether the value is a known member of the KeypairKind enum.
func (e KeypairKind) Valid() bool {
	switch e {
	case KeypairKindKeypair:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecForProviderProjectIDRefPolicyResolution.
const (
	KeypairSpecForProviderProjectIDRefPolicyResolutionOptional KeypairSpecForProviderProjectIDRefPolicyResolution = "Optional"
	KeypairSpecForProviderProjectIDRefPolicyResolutionRequired KeypairSpecForProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the KeypairSpecForProviderProjectIDRefPolicyResolution enum.
func (e KeypairSpecForProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case KeypairSpecForProviderProjectIDRefPolicyResolutionOptional:
		return true
	case KeypairSpecForProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecForProviderProjectIDRefPolicyResolve.
const (
	KeypairSpecForProviderProjectIDRefPolicyResolveAlways       KeypairSpecForProviderProjectIDRefPolicyResolve = "Always"
	KeypairSpecForProviderProjectIDRefPolicyResolveIfNotPresent KeypairSpecForProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the KeypairSpecForProviderProjectIDRefPolicyResolve enum.
func (e KeypairSpecForProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case KeypairSpecForProviderProjectIDRefPolicyResolveAlways:
		return true
	case KeypairSpecForProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecForProviderProjectIDSelectorPolicyResolution.
const (
	KeypairSpecForProviderProjectIDSelectorPolicyResolutionOptional KeypairSpecForProviderProjectIDSelectorPolicyResolution = "Optional"
	KeypairSpecForProviderProjectIDSelectorPolicyResolutionRequired KeypairSpecForProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the KeypairSpecForProviderProjectIDSelectorPolicyResolution enum.
func (e KeypairSpecForProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case KeypairSpecForProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case KeypairSpecForProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecForProviderProjectIDSelectorPolicyResolve.
const (
	KeypairSpecForProviderProjectIDSelectorPolicyResolveAlways       KeypairSpecForProviderProjectIDSelectorPolicyResolve = "Always"
	KeypairSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent KeypairSpecForProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the KeypairSpecForProviderProjectIDSelectorPolicyResolve enum.
func (e KeypairSpecForProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case KeypairSpecForProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case KeypairSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecInitProviderProjectIDRefPolicyResolution.
const (
	KeypairSpecInitProviderProjectIDRefPolicyResolutionOptional KeypairSpecInitProviderProjectIDRefPolicyResolution = "Optional"
	KeypairSpecInitProviderProjectIDRefPolicyResolutionRequired KeypairSpecInitProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the KeypairSpecInitProviderProjectIDRefPolicyResolution enum.
func (e KeypairSpecInitProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case KeypairSpecInitProviderProjectIDRefPolicyResolutionOptional:
		return true
	case KeypairSpecInitProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecInitProviderProjectIDRefPolicyResolve.
const (
	KeypairSpecInitProviderProjectIDRefPolicyResolveAlways       KeypairSpecInitProviderProjectIDRefPolicyResolve = "Always"
	KeypairSpecInitProviderProjectIDRefPolicyResolveIfNotPresent KeypairSpecInitProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the KeypairSpecInitProviderProjectIDRefPolicyResolve enum.
func (e KeypairSpecInitProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case KeypairSpecInitProviderProjectIDRefPolicyResolveAlways:
		return true
	case KeypairSpecInitProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecInitProviderProjectIDSelectorPolicyResolution.
const (
	KeypairSpecInitProviderProjectIDSelectorPolicyResolutionOptional KeypairSpecInitProviderProjectIDSelectorPolicyResolution = "Optional"
	KeypairSpecInitProviderProjectIDSelectorPolicyResolutionRequired KeypairSpecInitProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the KeypairSpecInitProviderProjectIDSelectorPolicyResolution enum.
func (e KeypairSpecInitProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case KeypairSpecInitProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case KeypairSpecInitProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecInitProviderProjectIDSelectorPolicyResolve.
const (
	KeypairSpecInitProviderProjectIDSelectorPolicyResolveAlways       KeypairSpecInitProviderProjectIDSelectorPolicyResolve = "Always"
	KeypairSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent KeypairSpecInitProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the KeypairSpecInitProviderProjectIDSelectorPolicyResolve enum.
func (e KeypairSpecInitProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case KeypairSpecInitProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case KeypairSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for KeypairSpecManagementPoliciesItem.
const (
	KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItem               KeypairSpecManagementPoliciesItem = "*"
	KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemCreate         KeypairSpecManagementPoliciesItem = "Create"
	KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemDelete         KeypairSpecManagementPoliciesItem = "Delete"
	KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemLateInitialize KeypairSpecManagementPoliciesItem = "LateInitialize"
	KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemObserve        KeypairSpecManagementPoliciesItem = "Observe"
	KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemUpdate         KeypairSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the KeypairSpecManagementPoliciesItem enum.
func (e KeypairSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItem:
		return true
	case KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemCreate:
		return true
	case KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemDelete:
		return true
	case KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemLateInitialize:
		return true
	case KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemObserve:
		return true
	case KeypairSpecManagementPoliciesItemKeypairSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoCrossplaneArubacloudV1Alpha1Keypair Keypair is the Schema for the Keypairs API. Manages an ArubaCloud SSH KeyPair.
type IoCrossplaneArubacloudV1Alpha1Keypair = Keypair

// KeypairAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type KeypairAPIVersion string

// KeypairKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type KeypairKind string

// KeypairSpecForProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type KeypairSpecForProviderProjectIDRefPolicyResolution string

// KeypairSpecForProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type KeypairSpecForProviderProjectIDRefPolicyResolve string

// KeypairSpecForProviderProjectIDRefPolicy Policies for referencing.
type KeypairSpecForProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *KeypairSpecForProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *KeypairSpecForProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// KeypairSpecForProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type KeypairSpecForProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *KeypairSpecForProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// KeypairSpecForProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type KeypairSpecForProviderProjectIDSelectorPolicyResolution string

// KeypairSpecForProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type KeypairSpecForProviderProjectIDSelectorPolicyResolve string

// KeypairSpecForProviderProjectIDSelectorPolicy Policies for selection.
type KeypairSpecForProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *KeypairSpecForProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *KeypairSpecForProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// KeypairSpecForProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type KeypairSpecForProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *KeypairSpecForProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// KeypairSpecForProviderValueSecretRef format public key string (e.g., ssh-rsa AAAA...). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
// OpenSSH-format public key string (e.g., `ssh-rsa AAAA...`). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
type KeypairSpecForProviderValueSecretRef struct {
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// KeypairSpecForProvider defines model for .
type KeypairSpecForProvider struct {
	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name created.)
	// Display name for the KeyPair. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *KeypairSpecForProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *KeypairSpecForProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// ValueSecretRef format public key string (e.g., ssh-rsa AAAA...). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// OpenSSH-format public key string (e.g., `ssh-rsa AAAA...`). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ValueSecretRef *KeypairSpecForProviderValueSecretRef `json:"valueSecretRef,omitempty"`
}

// KeypairSpecInitProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type KeypairSpecInitProviderProjectIDRefPolicyResolution string

// KeypairSpecInitProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type KeypairSpecInitProviderProjectIDRefPolicyResolve string

// KeypairSpecInitProviderProjectIDRefPolicy Policies for referencing.
type KeypairSpecInitProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *KeypairSpecInitProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *KeypairSpecInitProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// KeypairSpecInitProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type KeypairSpecInitProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *KeypairSpecInitProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// KeypairSpecInitProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type KeypairSpecInitProviderProjectIDSelectorPolicyResolution string

// KeypairSpecInitProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type KeypairSpecInitProviderProjectIDSelectorPolicyResolve string

// KeypairSpecInitProviderProjectIDSelectorPolicy Policies for selection.
type KeypairSpecInitProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *KeypairSpecInitProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *KeypairSpecInitProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// KeypairSpecInitProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type KeypairSpecInitProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *KeypairSpecInitProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// KeypairSpecInitProviderValueSecretRef format public key string (e.g., ssh-rsa AAAA...). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
// OpenSSH-format public key string (e.g., `ssh-rsa AAAA...`). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
type KeypairSpecInitProviderValueSecretRef struct {
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// KeypairSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type KeypairSpecInitProvider struct {
	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name created.)
	// Display name for the KeyPair. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *KeypairSpecInitProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *KeypairSpecInitProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// ValueSecretRef format public key string (e.g., ssh-rsa AAAA...). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// OpenSSH-format public key string (e.g., `ssh-rsa AAAA...`). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ValueSecretRef *KeypairSpecInitProviderValueSecretRef `json:"valueSecretRef,omitempty"`
}

// KeypairSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type KeypairSpecManagementPoliciesItem string

// KeypairSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type KeypairSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// KeypairSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type KeypairSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// KeypairSpec KeypairSpec defines the desired state of Keypair
type KeypairSpec struct {
	ForProvider *KeypairSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *KeypairSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]KeypairSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *KeypairSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *KeypairSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// KeypairStatusAtProvider defines model for .
type KeypairStatusAtProvider struct {
	// ID (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name created.)
	// Display name for the KeyPair. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// URI (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty"`
}

// KeypairStatusConditionsItem A Condition that may apply to a resource.
type KeypairStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// KeypairStatus KeypairStatus defines the observed state of Keypair.
type KeypairStatus struct {
	AtProvider *KeypairStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]KeypairStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Keypair Keypair is the Schema for the Keypairs API. Manages an ArubaCloud SSH KeyPair.
type Keypair struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *KeypairAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *KeypairKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec KeypairSpec defines the desired state of Keypair
	Spec *KeypairSpec `json:"spec,omitempty"`

	// Status KeypairStatus defines the observed state of Keypair.
	Status *KeypairStatus `json:"status,omitempty"`
}

// IoCrossplaneArubacloudV1Alpha1KeypairList KeypairList is a list of Keypair
type IoCrossplaneArubacloudV1Alpha1KeypairList = KeypairList

// KeypairList KeypairList is a list of Keypair
type KeypairList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of keypairs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneArubacloudV1Alpha1Keypair `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
