// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ProjectAPIVersion.
const (
	ProjectAPIVersionArubacloudCrossplaneIoV1Alpha1 ProjectAPIVersion = "arubacloud.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ProjectAPIVersion enum.
func (e ProjectAPIVersion) Valid() bool {
	switch e {
	case ProjectAPIVersionArubacloudCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ProjectKind.
const (
	ProjectKindProject ProjectKind = "Project"
)

// Valid indicates whether the value is a known member of the ProjectKind enum.
func (e ProjectKind) Valid() bool {
	switch e {
	case ProjectKindProject:
		return true
	default:
		return false
	}
}

// Defines values for ProjectSpecManagementPoliciesItem.
const (
	ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItem               ProjectSpecManagementPoliciesItem = "*"
	ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemCreate         ProjectSpecManagementPoliciesItem = "Create"
	ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemDelete         ProjectSpecManagementPoliciesItem = "Delete"
	ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemLateInitialize ProjectSpecManagementPoliciesItem = "LateInitialize"
	ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemObserve        ProjectSpecManagementPoliciesItem = "Observe"
	ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemUpdate         ProjectSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the ProjectSpecManagementPoliciesItem enum.
func (e ProjectSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItem:
		return true
	case ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemCreate:
		return true
	case ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemDelete:
		return true
	case ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemLateInitialize:
		return true
	case ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemObserve:
		return true
	case ProjectSpecManagementPoliciesItemProjectSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoCrossplaneArubacloudV1Alpha1Project Project is the Schema for the Projects API. Manages an ArubaCloud Project — the top-level organisational unit for all resources.
type IoCrossplaneArubacloudV1Alpha1Project = Project

// ProjectAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ProjectAPIVersion string

// ProjectKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ProjectKind string

// ProjectSpecForProvider defines model for .
type ProjectSpecForProvider struct {
	// Description readable description of the project.
	// Optional human-readable description of the project.
	Description *string `json:"description,omitempty"`

	// Name (String) Display name for the Project.
	// Display name for the Project.
	Name *string `json:"name,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`
}

// ProjectSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type ProjectSpecInitProvider struct {
	// Description readable description of the project.
	// Optional human-readable description of the project.
	Description *string `json:"description,omitempty"`

	// Name (String) Display name for the Project.
	// Display name for the Project.
	Name *string `json:"name,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`
}

// ProjectSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type ProjectSpecManagementPoliciesItem string

// ProjectSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type ProjectSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// ProjectSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type ProjectSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// ProjectSpec ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	ForProvider *ProjectSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *ProjectSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]ProjectSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *ProjectSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *ProjectSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// ProjectStatusAtProvider defines model for .
type ProjectStatusAtProvider struct {
	// Description readable description of the project.
	// Optional human-readable description of the project.
	Description *string `json:"description,omitempty"`

	// ID (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty"`

	// Name (String) Display name for the Project.
	// Display name for the Project.
	Name *string `json:"name,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`
}

// ProjectStatusConditionsItem A Condition that may apply to a resource.
type ProjectStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ProjectStatus ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	AtProvider *ProjectStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]ProjectStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Project Project is the Schema for the Projects API. Manages an ArubaCloud Project — the top-level organisational unit for all resources.
type Project struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ProjectAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ProjectKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec ProjectSpec defines the desired state of Project
	Spec *ProjectSpec `json:"spec,omitempty"`

	// Status ProjectStatus defines the observed state of Project.
	Status *ProjectStatus `json:"status,omitempty"`
}

// IoCrossplaneArubacloudV1Alpha1ProjectList ProjectList is a list of Project
type IoCrossplaneArubacloudV1Alpha1ProjectList = ProjectList

// ProjectList ProjectList is a list of Project
type ProjectList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of projects. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneArubacloudV1Alpha1Project `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
