// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for SnapshotAPIVersion.
const (
	SnapshotAPIVersionArubacloudCrossplaneIoV1Alpha1 SnapshotAPIVersion = "arubacloud.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the SnapshotAPIVersion enum.
func (e SnapshotAPIVersion) Valid() bool {
	switch e {
	case SnapshotAPIVersionArubacloudCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotKind.
const (
	SnapshotKindSnapshot SnapshotKind = "Snapshot"
)

// Valid indicates whether the value is a known member of the SnapshotKind enum.
func (e SnapshotKind) Valid() bool {
	switch e {
	case SnapshotKindSnapshot:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderProjectIDRefPolicyResolution.
const (
	SnapshotSpecForProviderProjectIDRefPolicyResolutionOptional SnapshotSpecForProviderProjectIDRefPolicyResolution = "Optional"
	SnapshotSpecForProviderProjectIDRefPolicyResolutionRequired SnapshotSpecForProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderProjectIDRefPolicyResolution enum.
func (e SnapshotSpecForProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecForProviderProjectIDRefPolicyResolutionOptional:
		return true
	case SnapshotSpecForProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderProjectIDRefPolicyResolve.
const (
	SnapshotSpecForProviderProjectIDRefPolicyResolveAlways       SnapshotSpecForProviderProjectIDRefPolicyResolve = "Always"
	SnapshotSpecForProviderProjectIDRefPolicyResolveIfNotPresent SnapshotSpecForProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderProjectIDRefPolicyResolve enum.
func (e SnapshotSpecForProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecForProviderProjectIDRefPolicyResolveAlways:
		return true
	case SnapshotSpecForProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderProjectIDSelectorPolicyResolution.
const (
	SnapshotSpecForProviderProjectIDSelectorPolicyResolutionOptional SnapshotSpecForProviderProjectIDSelectorPolicyResolution = "Optional"
	SnapshotSpecForProviderProjectIDSelectorPolicyResolutionRequired SnapshotSpecForProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderProjectIDSelectorPolicyResolution enum.
func (e SnapshotSpecForProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecForProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case SnapshotSpecForProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderProjectIDSelectorPolicyResolve.
const (
	SnapshotSpecForProviderProjectIDSelectorPolicyResolveAlways       SnapshotSpecForProviderProjectIDSelectorPolicyResolve = "Always"
	SnapshotSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent SnapshotSpecForProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderProjectIDSelectorPolicyResolve enum.
func (e SnapshotSpecForProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecForProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case SnapshotSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderVolumeURIRefPolicyResolution.
const (
	SnapshotSpecForProviderVolumeURIRefPolicyResolutionOptional SnapshotSpecForProviderVolumeURIRefPolicyResolution = "Optional"
	SnapshotSpecForProviderVolumeURIRefPolicyResolutionRequired SnapshotSpecForProviderVolumeURIRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderVolumeURIRefPolicyResolution enum.
func (e SnapshotSpecForProviderVolumeURIRefPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecForProviderVolumeURIRefPolicyResolutionOptional:
		return true
	case SnapshotSpecForProviderVolumeURIRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderVolumeURIRefPolicyResolve.
const (
	SnapshotSpecForProviderVolumeURIRefPolicyResolveAlways       SnapshotSpecForProviderVolumeURIRefPolicyResolve = "Always"
	SnapshotSpecForProviderVolumeURIRefPolicyResolveIfNotPresent SnapshotSpecForProviderVolumeURIRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderVolumeURIRefPolicyResolve enum.
func (e SnapshotSpecForProviderVolumeURIRefPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecForProviderVolumeURIRefPolicyResolveAlways:
		return true
	case SnapshotSpecForProviderVolumeURIRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderVolumeURISelectorPolicyResolution.
const (
	SnapshotSpecForProviderVolumeURISelectorPolicyResolutionOptional SnapshotSpecForProviderVolumeURISelectorPolicyResolution = "Optional"
	SnapshotSpecForProviderVolumeURISelectorPolicyResolutionRequired SnapshotSpecForProviderVolumeURISelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderVolumeURISelectorPolicyResolution enum.
func (e SnapshotSpecForProviderVolumeURISelectorPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecForProviderVolumeURISelectorPolicyResolutionOptional:
		return true
	case SnapshotSpecForProviderVolumeURISelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecForProviderVolumeURISelectorPolicyResolve.
const (
	SnapshotSpecForProviderVolumeURISelectorPolicyResolveAlways       SnapshotSpecForProviderVolumeURISelectorPolicyResolve = "Always"
	SnapshotSpecForProviderVolumeURISelectorPolicyResolveIfNotPresent SnapshotSpecForProviderVolumeURISelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecForProviderVolumeURISelectorPolicyResolve enum.
func (e SnapshotSpecForProviderVolumeURISelectorPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecForProviderVolumeURISelectorPolicyResolveAlways:
		return true
	case SnapshotSpecForProviderVolumeURISelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderProjectIDRefPolicyResolution.
const (
	SnapshotSpecInitProviderProjectIDRefPolicyResolutionOptional SnapshotSpecInitProviderProjectIDRefPolicyResolution = "Optional"
	SnapshotSpecInitProviderProjectIDRefPolicyResolutionRequired SnapshotSpecInitProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderProjectIDRefPolicyResolution enum.
func (e SnapshotSpecInitProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderProjectIDRefPolicyResolutionOptional:
		return true
	case SnapshotSpecInitProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderProjectIDRefPolicyResolve.
const (
	SnapshotSpecInitProviderProjectIDRefPolicyResolveAlways       SnapshotSpecInitProviderProjectIDRefPolicyResolve = "Always"
	SnapshotSpecInitProviderProjectIDRefPolicyResolveIfNotPresent SnapshotSpecInitProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderProjectIDRefPolicyResolve enum.
func (e SnapshotSpecInitProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderProjectIDRefPolicyResolveAlways:
		return true
	case SnapshotSpecInitProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderProjectIDSelectorPolicyResolution.
const (
	SnapshotSpecInitProviderProjectIDSelectorPolicyResolutionOptional SnapshotSpecInitProviderProjectIDSelectorPolicyResolution = "Optional"
	SnapshotSpecInitProviderProjectIDSelectorPolicyResolutionRequired SnapshotSpecInitProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderProjectIDSelectorPolicyResolution enum.
func (e SnapshotSpecInitProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case SnapshotSpecInitProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderProjectIDSelectorPolicyResolve.
const (
	SnapshotSpecInitProviderProjectIDSelectorPolicyResolveAlways       SnapshotSpecInitProviderProjectIDSelectorPolicyResolve = "Always"
	SnapshotSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent SnapshotSpecInitProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderProjectIDSelectorPolicyResolve enum.
func (e SnapshotSpecInitProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case SnapshotSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderVolumeURIRefPolicyResolution.
const (
	SnapshotSpecInitProviderVolumeURIRefPolicyResolutionOptional SnapshotSpecInitProviderVolumeURIRefPolicyResolution = "Optional"
	SnapshotSpecInitProviderVolumeURIRefPolicyResolutionRequired SnapshotSpecInitProviderVolumeURIRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderVolumeURIRefPolicyResolution enum.
func (e SnapshotSpecInitProviderVolumeURIRefPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderVolumeURIRefPolicyResolutionOptional:
		return true
	case SnapshotSpecInitProviderVolumeURIRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderVolumeURIRefPolicyResolve.
const (
	SnapshotSpecInitProviderVolumeURIRefPolicyResolveAlways       SnapshotSpecInitProviderVolumeURIRefPolicyResolve = "Always"
	SnapshotSpecInitProviderVolumeURIRefPolicyResolveIfNotPresent SnapshotSpecInitProviderVolumeURIRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderVolumeURIRefPolicyResolve enum.
func (e SnapshotSpecInitProviderVolumeURIRefPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderVolumeURIRefPolicyResolveAlways:
		return true
	case SnapshotSpecInitProviderVolumeURIRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderVolumeURISelectorPolicyResolution.
const (
	SnapshotSpecInitProviderVolumeURISelectorPolicyResolutionOptional SnapshotSpecInitProviderVolumeURISelectorPolicyResolution = "Optional"
	SnapshotSpecInitProviderVolumeURISelectorPolicyResolutionRequired SnapshotSpecInitProviderVolumeURISelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderVolumeURISelectorPolicyResolution enum.
func (e SnapshotSpecInitProviderVolumeURISelectorPolicyResolution) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderVolumeURISelectorPolicyResolutionOptional:
		return true
	case SnapshotSpecInitProviderVolumeURISelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecInitProviderVolumeURISelectorPolicyResolve.
const (
	SnapshotSpecInitProviderVolumeURISelectorPolicyResolveAlways       SnapshotSpecInitProviderVolumeURISelectorPolicyResolve = "Always"
	SnapshotSpecInitProviderVolumeURISelectorPolicyResolveIfNotPresent SnapshotSpecInitProviderVolumeURISelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SnapshotSpecInitProviderVolumeURISelectorPolicyResolve enum.
func (e SnapshotSpecInitProviderVolumeURISelectorPolicyResolve) Valid() bool {
	switch e {
	case SnapshotSpecInitProviderVolumeURISelectorPolicyResolveAlways:
		return true
	case SnapshotSpecInitProviderVolumeURISelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSpecManagementPoliciesItem.
const (
	SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItem               SnapshotSpecManagementPoliciesItem = "*"
	SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemCreate         SnapshotSpecManagementPoliciesItem = "Create"
	SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemDelete         SnapshotSpecManagementPoliciesItem = "Delete"
	SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemLateInitialize SnapshotSpecManagementPoliciesItem = "LateInitialize"
	SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemObserve        SnapshotSpecManagementPoliciesItem = "Observe"
	SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemUpdate         SnapshotSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the SnapshotSpecManagementPoliciesItem enum.
func (e SnapshotSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItem:
		return true
	case SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemCreate:
		return true
	case SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemDelete:
		return true
	case SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemLateInitialize:
		return true
	case SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemObserve:
		return true
	case SnapshotSpecManagementPoliciesItemSnapshotSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoCrossplaneArubacloudV1Alpha1Snapshot Snapshot is the Schema for the Snapshots API. Manages an ArubaCloud Snapshot — a point-in-time copy of a block storage volume.
type IoCrossplaneArubacloudV1Alpha1Snapshot = Snapshot

// SnapshotAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type SnapshotAPIVersion string

// SnapshotKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type SnapshotKind string

// SnapshotSpecForProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecForProviderProjectIDRefPolicyResolution string

// SnapshotSpecForProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecForProviderProjectIDRefPolicyResolve string

// SnapshotSpecForProviderProjectIDRefPolicy Policies for referencing.
type SnapshotSpecForProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecForProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecForProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecForProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type SnapshotSpecForProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SnapshotSpecForProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// SnapshotSpecForProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecForProviderProjectIDSelectorPolicyResolution string

// SnapshotSpecForProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecForProviderProjectIDSelectorPolicyResolve string

// SnapshotSpecForProviderProjectIDSelectorPolicy Policies for selection.
type SnapshotSpecForProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecForProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecForProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecForProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type SnapshotSpecForProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SnapshotSpecForProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// SnapshotSpecForProviderVolumeURIRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecForProviderVolumeURIRefPolicyResolution string

// SnapshotSpecForProviderVolumeURIRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecForProviderVolumeURIRefPolicyResolve string

// SnapshotSpecForProviderVolumeURIRefPolicy Policies for referencing.
type SnapshotSpecForProviderVolumeURIRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecForProviderVolumeURIRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecForProviderVolumeURIRefPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecForProviderVolumeURIRef Reference to a Blockstorage in arubacloud to populate volumeUri.
type SnapshotSpecForProviderVolumeURIRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SnapshotSpecForProviderVolumeURIRefPolicy `json:"policy,omitempty"`
}

// SnapshotSpecForProviderVolumeURISelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecForProviderVolumeURISelectorPolicyResolution string

// SnapshotSpecForProviderVolumeURISelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecForProviderVolumeURISelectorPolicyResolve string

// SnapshotSpecForProviderVolumeURISelectorPolicy Policies for selection.
type SnapshotSpecForProviderVolumeURISelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecForProviderVolumeURISelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecForProviderVolumeURISelectorPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecForProviderVolumeURISelector Selector for a Blockstorage in arubacloud to populate volumeUri.
type SnapshotSpecForProviderVolumeURISelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SnapshotSpecForProviderVolumeURISelectorPolicy `json:"policy,omitempty"`
}

// SnapshotSpecForProvider defines model for .
type SnapshotSpecForProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the snapshot.
	// Display name for the snapshot.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *SnapshotSpecForProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *SnapshotSpecForProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// VolumeURI created.)
	// URI of the block storage volume this snapshot is taken from. Reference the `uri` attribute of an `arubacloud_blockstorage` resource (e.g., `/projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	VolumeURI *string `json:"volumeUri,omitempty"`

	// VolumeURIRef Reference to a Blockstorage in arubacloud to populate volumeUri.
	VolumeURIRef *SnapshotSpecForProviderVolumeURIRef `json:"volumeUriRef,omitempty"`

	// VolumeURISelector Selector for a Blockstorage in arubacloud to populate volumeUri.
	VolumeURISelector *SnapshotSpecForProviderVolumeURISelector `json:"volumeUriSelector,omitempty"`
}

// SnapshotSpecInitProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecInitProviderProjectIDRefPolicyResolution string

// SnapshotSpecInitProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecInitProviderProjectIDRefPolicyResolve string

// SnapshotSpecInitProviderProjectIDRefPolicy Policies for referencing.
type SnapshotSpecInitProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecInitProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecInitProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecInitProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type SnapshotSpecInitProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SnapshotSpecInitProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// SnapshotSpecInitProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecInitProviderProjectIDSelectorPolicyResolution string

// SnapshotSpecInitProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecInitProviderProjectIDSelectorPolicyResolve string

// SnapshotSpecInitProviderProjectIDSelectorPolicy Policies for selection.
type SnapshotSpecInitProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecInitProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecInitProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecInitProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type SnapshotSpecInitProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SnapshotSpecInitProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// SnapshotSpecInitProviderVolumeURIRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecInitProviderVolumeURIRefPolicyResolution string

// SnapshotSpecInitProviderVolumeURIRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecInitProviderVolumeURIRefPolicyResolve string

// SnapshotSpecInitProviderVolumeURIRefPolicy Policies for referencing.
type SnapshotSpecInitProviderVolumeURIRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecInitProviderVolumeURIRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecInitProviderVolumeURIRefPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecInitProviderVolumeURIRef Reference to a Blockstorage in arubacloud to populate volumeUri.
type SnapshotSpecInitProviderVolumeURIRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SnapshotSpecInitProviderVolumeURIRefPolicy `json:"policy,omitempty"`
}

// SnapshotSpecInitProviderVolumeURISelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SnapshotSpecInitProviderVolumeURISelectorPolicyResolution string

// SnapshotSpecInitProviderVolumeURISelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SnapshotSpecInitProviderVolumeURISelectorPolicyResolve string

// SnapshotSpecInitProviderVolumeURISelectorPolicy Policies for selection.
type SnapshotSpecInitProviderVolumeURISelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SnapshotSpecInitProviderVolumeURISelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SnapshotSpecInitProviderVolumeURISelectorPolicyResolve `json:"resolve,omitempty"`
}

// SnapshotSpecInitProviderVolumeURISelector Selector for a Blockstorage in arubacloud to populate volumeUri.
type SnapshotSpecInitProviderVolumeURISelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SnapshotSpecInitProviderVolumeURISelectorPolicy `json:"policy,omitempty"`
}

// SnapshotSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type SnapshotSpecInitProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the snapshot.
	// Display name for the snapshot.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *SnapshotSpecInitProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *SnapshotSpecInitProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// VolumeURI created.)
	// URI of the block storage volume this snapshot is taken from. Reference the `uri` attribute of an `arubacloud_blockstorage` resource (e.g., `/projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	VolumeURI *string `json:"volumeUri,omitempty"`

	// VolumeURIRef Reference to a Blockstorage in arubacloud to populate volumeUri.
	VolumeURIRef *SnapshotSpecInitProviderVolumeURIRef `json:"volumeUriRef,omitempty"`

	// VolumeURISelector Selector for a Blockstorage in arubacloud to populate volumeUri.
	VolumeURISelector *SnapshotSpecInitProviderVolumeURISelector `json:"volumeUriSelector,omitempty"`
}

// SnapshotSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type SnapshotSpecManagementPoliciesItem string

// SnapshotSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type SnapshotSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// SnapshotSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type SnapshotSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// SnapshotSpec SnapshotSpec defines the desired state of Snapshot
type SnapshotSpec struct {
	ForProvider *SnapshotSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *SnapshotSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]SnapshotSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *SnapshotSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *SnapshotSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// SnapshotStatusAtProvider defines model for .
type SnapshotStatusAtProvider struct {
	// BillingPeriod (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty"`

	// ID (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty"`

	// Location Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the snapshot.
	// Display name for the snapshot.
	Name *string `json:"name,omitempty"`

	// ProjectID created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// URI (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty"`

	// VolumeURI created.)
	// URI of the block storage volume this snapshot is taken from. Reference the `uri` attribute of an `arubacloud_blockstorage` resource (e.g., `/projects/{project_id}/providers/Aruba.Storage/volumes/{volume_id}`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	VolumeURI *string `json:"volumeUri,omitempty"`
}

// SnapshotStatusConditionsItem A Condition that may apply to a resource.
type SnapshotStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// SnapshotStatus SnapshotStatus defines the observed state of Snapshot.
type SnapshotStatus struct {
	AtProvider *SnapshotStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]SnapshotStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Snapshot Snapshot is the Schema for the Snapshots API. Manages an ArubaCloud Snapshot — a point-in-time copy of a block storage volume.
type Snapshot struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *SnapshotAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *SnapshotKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec SnapshotSpec defines the desired state of Snapshot
	Spec *SnapshotSpec `json:"spec,omitempty"`

	// Status SnapshotStatus defines the observed state of Snapshot.
	Status *SnapshotStatus `json:"status,omitempty"`
}

// IoCrossplaneArubacloudV1Alpha1SnapshotList SnapshotList is a list of Snapshot
type IoCrossplaneArubacloudV1Alpha1SnapshotList = SnapshotList

// SnapshotList SnapshotList is a list of Snapshot
type SnapshotList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of snapshots. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneArubacloudV1Alpha1Snapshot `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
