// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for VPCApiVersion.
const (
	VPCApiVersionArubacloudCrossplaneIoV1Alpha1 VPCApiVersion = "arubacloud.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the VPCApiVersion enum.
func (e VPCApiVersion) Valid() bool {
	switch e {
	case VPCApiVersionArubacloudCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for VPCKind.
const (
	VPCKindVPC VPCKind = "VPC"
)

// Valid indicates whether the value is a known member of the VPCKind enum.
func (e VPCKind) Valid() bool {
	switch e {
	case VPCKindVPC:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecForProviderProjectIDRefPolicyResolution.
const (
	VPCSpecForProviderProjectIDRefPolicyResolutionOptional VPCSpecForProviderProjectIDRefPolicyResolution = "Optional"
	VPCSpecForProviderProjectIDRefPolicyResolutionRequired VPCSpecForProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCSpecForProviderProjectIDRefPolicyResolution enum.
func (e VPCSpecForProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCSpecForProviderProjectIDRefPolicyResolutionOptional:
		return true
	case VPCSpecForProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecForProviderProjectIDRefPolicyResolve.
const (
	VPCSpecForProviderProjectIDRefPolicyResolveAlways       VPCSpecForProviderProjectIDRefPolicyResolve = "Always"
	VPCSpecForProviderProjectIDRefPolicyResolveIfNotPresent VPCSpecForProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCSpecForProviderProjectIDRefPolicyResolve enum.
func (e VPCSpecForProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCSpecForProviderProjectIDRefPolicyResolveAlways:
		return true
	case VPCSpecForProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecForProviderProjectIDSelectorPolicyResolution.
const (
	VPCSpecForProviderProjectIDSelectorPolicyResolutionOptional VPCSpecForProviderProjectIDSelectorPolicyResolution = "Optional"
	VPCSpecForProviderProjectIDSelectorPolicyResolutionRequired VPCSpecForProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCSpecForProviderProjectIDSelectorPolicyResolution enum.
func (e VPCSpecForProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCSpecForProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case VPCSpecForProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecForProviderProjectIDSelectorPolicyResolve.
const (
	VPCSpecForProviderProjectIDSelectorPolicyResolveAlways       VPCSpecForProviderProjectIDSelectorPolicyResolve = "Always"
	VPCSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent VPCSpecForProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCSpecForProviderProjectIDSelectorPolicyResolve enum.
func (e VPCSpecForProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCSpecForProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case VPCSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecInitProviderProjectIDRefPolicyResolution.
const (
	VPCSpecInitProviderProjectIDRefPolicyResolutionOptional VPCSpecInitProviderProjectIDRefPolicyResolution = "Optional"
	VPCSpecInitProviderProjectIDRefPolicyResolutionRequired VPCSpecInitProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCSpecInitProviderProjectIDRefPolicyResolution enum.
func (e VPCSpecInitProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCSpecInitProviderProjectIDRefPolicyResolutionOptional:
		return true
	case VPCSpecInitProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecInitProviderProjectIDRefPolicyResolve.
const (
	VPCSpecInitProviderProjectIDRefPolicyResolveAlways       VPCSpecInitProviderProjectIDRefPolicyResolve = "Always"
	VPCSpecInitProviderProjectIDRefPolicyResolveIfNotPresent VPCSpecInitProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCSpecInitProviderProjectIDRefPolicyResolve enum.
func (e VPCSpecInitProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCSpecInitProviderProjectIDRefPolicyResolveAlways:
		return true
	case VPCSpecInitProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecInitProviderProjectIDSelectorPolicyResolution.
const (
	VPCSpecInitProviderProjectIDSelectorPolicyResolutionOptional VPCSpecInitProviderProjectIDSelectorPolicyResolution = "Optional"
	VPCSpecInitProviderProjectIDSelectorPolicyResolutionRequired VPCSpecInitProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCSpecInitProviderProjectIDSelectorPolicyResolution enum.
func (e VPCSpecInitProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCSpecInitProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case VPCSpecInitProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecInitProviderProjectIDSelectorPolicyResolve.
const (
	VPCSpecInitProviderProjectIDSelectorPolicyResolveAlways       VPCSpecInitProviderProjectIDSelectorPolicyResolve = "Always"
	VPCSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent VPCSpecInitProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCSpecInitProviderProjectIDSelectorPolicyResolve enum.
func (e VPCSpecInitProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCSpecInitProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case VPCSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCSpecManagementPoliciesItem.
const (
	VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItem               VPCSpecManagementPoliciesItem = "*"
	VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemCreate         VPCSpecManagementPoliciesItem = "Create"
	VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemDelete         VPCSpecManagementPoliciesItem = "Delete"
	VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemLateInitialize VPCSpecManagementPoliciesItem = "LateInitialize"
	VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemObserve        VPCSpecManagementPoliciesItem = "Observe"
	VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemUpdate         VPCSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the VPCSpecManagementPoliciesItem enum.
func (e VPCSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItem:
		return true
	case VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemCreate:
		return true
	case VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemDelete:
		return true
	case VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemLateInitialize:
		return true
	case VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemObserve:
		return true
	case VPCSpecManagementPoliciesItemVPCSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoCrossplaneArubacloudV1Alpha1VPC VPC is the Schema for the VPCs API. Manages an ArubaCloud VPC (Virtual Private Cloud) — the isolated network boundary within a region where subnets, security groups, and server instances are provisioned.
type IoCrossplaneArubacloudV1Alpha1VPC = VPC

// VPCApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type VPCApiVersion string

// VPCKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type VPCKind string

// VPCSpecForProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCSpecForProviderProjectIDRefPolicyResolution string

// VPCSpecForProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCSpecForProviderProjectIDRefPolicyResolve string

// VPCSpecForProviderProjectIDRefPolicy Policies for referencing.
type VPCSpecForProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCSpecForProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCSpecForProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCSpecForProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type VPCSpecForProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCSpecForProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// VPCSpecForProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCSpecForProviderProjectIDSelectorPolicyResolution string

// VPCSpecForProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCSpecForProviderProjectIDSelectorPolicyResolve string

// VPCSpecForProviderProjectIDSelectorPolicy Policies for selection.
type VPCSpecForProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCSpecForProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCSpecForProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCSpecForProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type VPCSpecForProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VPCSpecForProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCSpecForProvider defines model for .
type VPCSpecForProvider struct {
	// Location Bergamo). Changing this value forces a new resource.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). Changing this value forces a new resource.
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the VPC.
	// Display name for the VPC.
	Name *string `json:"name,omitempty"`

	// ProjectID (String) ID of the project that owns this resource. Changing this value forces a new resource.
	// ID of the project that owns this resource. Changing this value forces a new resource.
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *VPCSpecForProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *VPCSpecForProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`
}

// VPCSpecInitProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCSpecInitProviderProjectIDRefPolicyResolution string

// VPCSpecInitProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCSpecInitProviderProjectIDRefPolicyResolve string

// VPCSpecInitProviderProjectIDRefPolicy Policies for referencing.
type VPCSpecInitProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCSpecInitProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCSpecInitProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCSpecInitProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type VPCSpecInitProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCSpecInitProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// VPCSpecInitProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCSpecInitProviderProjectIDSelectorPolicyResolution string

// VPCSpecInitProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCSpecInitProviderProjectIDSelectorPolicyResolve string

// VPCSpecInitProviderProjectIDSelectorPolicy Policies for selection.
type VPCSpecInitProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCSpecInitProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCSpecInitProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCSpecInitProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type VPCSpecInitProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VPCSpecInitProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type VPCSpecInitProvider struct {
	// Location Bergamo). Changing this value forces a new resource.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). Changing this value forces a new resource.
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the VPC.
	// Display name for the VPC.
	Name *string `json:"name,omitempty"`

	// ProjectID (String) ID of the project that owns this resource. Changing this value forces a new resource.
	// ID of the project that owns this resource. Changing this value forces a new resource.
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *VPCSpecInitProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *VPCSpecInitProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`
}

// VPCSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type VPCSpecManagementPoliciesItem string

// VPCSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type VPCSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// VPCSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type VPCSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// VPCSpec VPCSpec defines the desired state of VPC
type VPCSpec struct {
	ForProvider *VPCSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *VPCSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]VPCSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *VPCSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *VPCSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// VPCStatusAtProvider defines model for .
type VPCStatusAtProvider struct {
	// ID (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty"`

	// Location Bergamo). Changing this value forces a new resource.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). Changing this value forces a new resource.
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the VPC.
	// Display name for the VPC.
	Name *string `json:"name,omitempty"`

	// ProjectID (String) ID of the project that owns this resource. Changing this value forces a new resource.
	// ID of the project that owns this resource. Changing this value forces a new resource.
	ProjectID *string `json:"projectId,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// URI (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty"`
}

// VPCStatusConditionsItem A Condition that may apply to a resource.
type VPCStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// VPCStatus VPCStatus defines the observed state of VPC.
type VPCStatus struct {
	AtProvider *VPCStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]VPCStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// VPC VPC is the Schema for the VPCs API. Manages an ArubaCloud VPC (Virtual Private Cloud) — the isolated network boundary within a region where subnets, security groups, and server instances are provisioned.
type VPC struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *VPCApiVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *VPCKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec VPCSpec defines the desired state of VPC
	Spec *VPCSpec `json:"spec,omitempty"`

	// Status VPCStatus defines the observed state of VPC.
	Status *VPCStatus `json:"status,omitempty"`
}

// IoCrossplaneArubacloudV1Alpha1VPCList VPCList is a list of VPC
type IoCrossplaneArubacloudV1Alpha1VPCList = VPCList

// VPCList VPCList is a list of VPC
type VPCList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of vpcs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneArubacloudV1Alpha1VPC `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
