// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for VpcpeeringAPIVersion.
const (
	VpcpeeringAPIVersionArubacloudCrossplaneIoV1Alpha1 VpcpeeringAPIVersion = "arubacloud.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the VpcpeeringAPIVersion enum.
func (e VpcpeeringAPIVersion) Valid() bool {
	switch e {
	case VpcpeeringAPIVersionArubacloudCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringKind.
const (
	VpcpeeringKindVpcpeering VpcpeeringKind = "Vpcpeering"
)

// Valid indicates whether the value is a known member of the VpcpeeringKind enum.
func (e VpcpeeringKind) Valid() bool {
	switch e {
	case VpcpeeringKindVpcpeering:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderPeerVpcRefPolicyResolution.
const (
	VpcpeeringSpecForProviderPeerVpcRefPolicyResolutionOptional VpcpeeringSpecForProviderPeerVpcRefPolicyResolution = "Optional"
	VpcpeeringSpecForProviderPeerVpcRefPolicyResolutionRequired VpcpeeringSpecForProviderPeerVpcRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderPeerVpcRefPolicyResolution enum.
func (e VpcpeeringSpecForProviderPeerVpcRefPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderPeerVpcRefPolicyResolutionOptional:
		return true
	case VpcpeeringSpecForProviderPeerVpcRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderPeerVpcRefPolicyResolve.
const (
	VpcpeeringSpecForProviderPeerVpcRefPolicyResolveAlways       VpcpeeringSpecForProviderPeerVpcRefPolicyResolve = "Always"
	VpcpeeringSpecForProviderPeerVpcRefPolicyResolveIfNotPresent VpcpeeringSpecForProviderPeerVpcRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderPeerVpcRefPolicyResolve enum.
func (e VpcpeeringSpecForProviderPeerVpcRefPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderPeerVpcRefPolicyResolveAlways:
		return true
	case VpcpeeringSpecForProviderPeerVpcRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution.
const (
	VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolutionOptional VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution = "Optional"
	VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolutionRequired VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution enum.
func (e VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolutionOptional:
		return true
	case VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve.
const (
	VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolveAlways       VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve = "Always"
	VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolveIfNotPresent VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve enum.
func (e VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolveAlways:
		return true
	case VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderProjectIDRefPolicyResolution.
const (
	VpcpeeringSpecForProviderProjectIDRefPolicyResolutionOptional VpcpeeringSpecForProviderProjectIDRefPolicyResolution = "Optional"
	VpcpeeringSpecForProviderProjectIDRefPolicyResolutionRequired VpcpeeringSpecForProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderProjectIDRefPolicyResolution enum.
func (e VpcpeeringSpecForProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderProjectIDRefPolicyResolutionOptional:
		return true
	case VpcpeeringSpecForProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderProjectIDRefPolicyResolve.
const (
	VpcpeeringSpecForProviderProjectIDRefPolicyResolveAlways       VpcpeeringSpecForProviderProjectIDRefPolicyResolve = "Always"
	VpcpeeringSpecForProviderProjectIDRefPolicyResolveIfNotPresent VpcpeeringSpecForProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderProjectIDRefPolicyResolve enum.
func (e VpcpeeringSpecForProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderProjectIDRefPolicyResolveAlways:
		return true
	case VpcpeeringSpecForProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution.
const (
	VpcpeeringSpecForProviderProjectIDSelectorPolicyResolutionOptional VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution = "Optional"
	VpcpeeringSpecForProviderProjectIDSelectorPolicyResolutionRequired VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution enum.
func (e VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case VpcpeeringSpecForProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve.
const (
	VpcpeeringSpecForProviderProjectIDSelectorPolicyResolveAlways       VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve = "Always"
	VpcpeeringSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve enum.
func (e VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case VpcpeeringSpecForProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderVpcIDRefPolicyResolution.
const (
	VpcpeeringSpecForProviderVpcIDRefPolicyResolutionOptional VpcpeeringSpecForProviderVpcIDRefPolicyResolution = "Optional"
	VpcpeeringSpecForProviderVpcIDRefPolicyResolutionRequired VpcpeeringSpecForProviderVpcIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderVpcIDRefPolicyResolution enum.
func (e VpcpeeringSpecForProviderVpcIDRefPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderVpcIDRefPolicyResolutionOptional:
		return true
	case VpcpeeringSpecForProviderVpcIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderVpcIDRefPolicyResolve.
const (
	VpcpeeringSpecForProviderVpcIDRefPolicyResolveAlways       VpcpeeringSpecForProviderVpcIDRefPolicyResolve = "Always"
	VpcpeeringSpecForProviderVpcIDRefPolicyResolveIfNotPresent VpcpeeringSpecForProviderVpcIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderVpcIDRefPolicyResolve enum.
func (e VpcpeeringSpecForProviderVpcIDRefPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderVpcIDRefPolicyResolveAlways:
		return true
	case VpcpeeringSpecForProviderVpcIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution.
const (
	VpcpeeringSpecForProviderVpcIDSelectorPolicyResolutionOptional VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution = "Optional"
	VpcpeeringSpecForProviderVpcIDSelectorPolicyResolutionRequired VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution enum.
func (e VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderVpcIDSelectorPolicyResolutionOptional:
		return true
	case VpcpeeringSpecForProviderVpcIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve.
const (
	VpcpeeringSpecForProviderVpcIDSelectorPolicyResolveAlways       VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve = "Always"
	VpcpeeringSpecForProviderVpcIDSelectorPolicyResolveIfNotPresent VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve enum.
func (e VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecForProviderVpcIDSelectorPolicyResolveAlways:
		return true
	case VpcpeeringSpecForProviderVpcIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution.
const (
	VpcpeeringSpecInitProviderPeerVpcRefPolicyResolutionOptional VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution = "Optional"
	VpcpeeringSpecInitProviderPeerVpcRefPolicyResolutionRequired VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution enum.
func (e VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderPeerVpcRefPolicyResolutionOptional:
		return true
	case VpcpeeringSpecInitProviderPeerVpcRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve.
const (
	VpcpeeringSpecInitProviderPeerVpcRefPolicyResolveAlways       VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve = "Always"
	VpcpeeringSpecInitProviderPeerVpcRefPolicyResolveIfNotPresent VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve enum.
func (e VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderPeerVpcRefPolicyResolveAlways:
		return true
	case VpcpeeringSpecInitProviderPeerVpcRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution.
const (
	VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolutionOptional VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution = "Optional"
	VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolutionRequired VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution enum.
func (e VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolutionOptional:
		return true
	case VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve.
const (
	VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolveAlways       VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve = "Always"
	VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolveIfNotPresent VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve enum.
func (e VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolveAlways:
		return true
	case VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderProjectIDRefPolicyResolution.
const (
	VpcpeeringSpecInitProviderProjectIDRefPolicyResolutionOptional VpcpeeringSpecInitProviderProjectIDRefPolicyResolution = "Optional"
	VpcpeeringSpecInitProviderProjectIDRefPolicyResolutionRequired VpcpeeringSpecInitProviderProjectIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderProjectIDRefPolicyResolution enum.
func (e VpcpeeringSpecInitProviderProjectIDRefPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderProjectIDRefPolicyResolutionOptional:
		return true
	case VpcpeeringSpecInitProviderProjectIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderProjectIDRefPolicyResolve.
const (
	VpcpeeringSpecInitProviderProjectIDRefPolicyResolveAlways       VpcpeeringSpecInitProviderProjectIDRefPolicyResolve = "Always"
	VpcpeeringSpecInitProviderProjectIDRefPolicyResolveIfNotPresent VpcpeeringSpecInitProviderProjectIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderProjectIDRefPolicyResolve enum.
func (e VpcpeeringSpecInitProviderProjectIDRefPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderProjectIDRefPolicyResolveAlways:
		return true
	case VpcpeeringSpecInitProviderProjectIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution.
const (
	VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolutionOptional VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution = "Optional"
	VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolutionRequired VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution enum.
func (e VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolutionOptional:
		return true
	case VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve.
const (
	VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolveAlways       VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve = "Always"
	VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve enum.
func (e VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolveAlways:
		return true
	case VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderVpcIDRefPolicyResolution.
const (
	VpcpeeringSpecInitProviderVpcIDRefPolicyResolutionOptional VpcpeeringSpecInitProviderVpcIDRefPolicyResolution = "Optional"
	VpcpeeringSpecInitProviderVpcIDRefPolicyResolutionRequired VpcpeeringSpecInitProviderVpcIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderVpcIDRefPolicyResolution enum.
func (e VpcpeeringSpecInitProviderVpcIDRefPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderVpcIDRefPolicyResolutionOptional:
		return true
	case VpcpeeringSpecInitProviderVpcIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderVpcIDRefPolicyResolve.
const (
	VpcpeeringSpecInitProviderVpcIDRefPolicyResolveAlways       VpcpeeringSpecInitProviderVpcIDRefPolicyResolve = "Always"
	VpcpeeringSpecInitProviderVpcIDRefPolicyResolveIfNotPresent VpcpeeringSpecInitProviderVpcIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderVpcIDRefPolicyResolve enum.
func (e VpcpeeringSpecInitProviderVpcIDRefPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderVpcIDRefPolicyResolveAlways:
		return true
	case VpcpeeringSpecInitProviderVpcIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution.
const (
	VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolutionOptional VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution = "Optional"
	VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolutionRequired VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution enum.
func (e VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolutionOptional:
		return true
	case VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve.
const (
	VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolveAlways       VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve = "Always"
	VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolveIfNotPresent VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve enum.
func (e VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolveAlways:
		return true
	case VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VpcpeeringSpecManagementPoliciesItem.
const (
	VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItem               VpcpeeringSpecManagementPoliciesItem = "*"
	VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemCreate         VpcpeeringSpecManagementPoliciesItem = "Create"
	VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemDelete         VpcpeeringSpecManagementPoliciesItem = "Delete"
	VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemLateInitialize VpcpeeringSpecManagementPoliciesItem = "LateInitialize"
	VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemObserve        VpcpeeringSpecManagementPoliciesItem = "Observe"
	VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemUpdate         VpcpeeringSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the VpcpeeringSpecManagementPoliciesItem enum.
func (e VpcpeeringSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItem:
		return true
	case VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemCreate:
		return true
	case VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemDelete:
		return true
	case VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemLateInitialize:
		return true
	case VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemObserve:
		return true
	case VpcpeeringSpecManagementPoliciesItemVpcpeeringSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoCrossplaneArubacloudV1Alpha1Vpcpeering Vpcpeering is the Schema for the Vpcpeerings API. Manages an ArubaCloud VPC Peering connection between two VPCs, enabling private routing between them.
type IoCrossplaneArubacloudV1Alpha1Vpcpeering = Vpcpeering

// VpcpeeringAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type VpcpeeringAPIVersion string

// VpcpeeringKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type VpcpeeringKind string

// VpcpeeringSpecForProviderPeerVpcRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecForProviderPeerVpcRefPolicyResolution string

// VpcpeeringSpecForProviderPeerVpcRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecForProviderPeerVpcRefPolicyResolve string

// VpcpeeringSpecForProviderPeerVpcRefPolicy Policies for referencing.
type VpcpeeringSpecForProviderPeerVpcRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecForProviderPeerVpcRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecForProviderPeerVpcRefPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecForProviderPeerVpcRef Reference to a VPC in arubacloud to populate peerVpc.
type VpcpeeringSpecForProviderPeerVpcRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VpcpeeringSpecForProviderPeerVpcRefPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution string

// VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve string

// VpcpeeringSpecForProviderPeerVpcSelectorPolicy Policies for selection.
type VpcpeeringSpecForProviderPeerVpcSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecForProviderPeerVpcSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecForProviderPeerVpcSelector Selector for a VPC in arubacloud to populate peerVpc.
type VpcpeeringSpecForProviderPeerVpcSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VpcpeeringSpecForProviderPeerVpcSelectorPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecForProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecForProviderProjectIDRefPolicyResolution string

// VpcpeeringSpecForProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecForProviderProjectIDRefPolicyResolve string

// VpcpeeringSpecForProviderProjectIDRefPolicy Policies for referencing.
type VpcpeeringSpecForProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecForProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecForProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecForProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type VpcpeeringSpecForProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VpcpeeringSpecForProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution string

// VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve string

// VpcpeeringSpecForProviderProjectIDSelectorPolicy Policies for selection.
type VpcpeeringSpecForProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecForProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecForProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecForProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type VpcpeeringSpecForProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VpcpeeringSpecForProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecForProviderVpcIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecForProviderVpcIDRefPolicyResolution string

// VpcpeeringSpecForProviderVpcIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecForProviderVpcIDRefPolicyResolve string

// VpcpeeringSpecForProviderVpcIDRefPolicy Policies for referencing.
type VpcpeeringSpecForProviderVpcIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecForProviderVpcIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecForProviderVpcIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecForProviderVpcIDRef Reference to a VPC in arubacloud to populate vpcId.
type VpcpeeringSpecForProviderVpcIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VpcpeeringSpecForProviderVpcIDRefPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution string

// VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve string

// VpcpeeringSpecForProviderVpcIDSelectorPolicy Policies for selection.
type VpcpeeringSpecForProviderVpcIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecForProviderVpcIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecForProviderVpcIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecForProviderVpcIDSelector Selector for a VPC in arubacloud to populate vpcId.
type VpcpeeringSpecForProviderVpcIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VpcpeeringSpecForProviderVpcIDSelectorPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecForProvider defines model for .
type VpcpeeringSpecForProvider struct {
	// Location Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	Name *string `json:"name,omitempty"`

	// PeerVpc (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	PeerVpc *string `json:"peerVpc,omitempty"`

	// PeerVpcRef Reference to a VPC in arubacloud to populate peerVpc.
	PeerVpcRef *VpcpeeringSpecForProviderPeerVpcRef `json:"peerVpcRef,omitempty"`

	// PeerVpcSelector Selector for a VPC in arubacloud to populate peerVpc.
	PeerVpcSelector *VpcpeeringSpecForProviderPeerVpcSelector `json:"peerVpcSelector,omitempty"`

	// ProjectID (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *VpcpeeringSpecForProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *VpcpeeringSpecForProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// VpcID (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	VpcID *string `json:"vpcId,omitempty"`

	// VpcIDRef Reference to a VPC in arubacloud to populate vpcId.
	VpcIDRef *VpcpeeringSpecForProviderVpcIDRef `json:"vpcIdRef,omitempty"`

	// VpcIDSelector Selector for a VPC in arubacloud to populate vpcId.
	VpcIDSelector *VpcpeeringSpecForProviderVpcIDSelector `json:"vpcIdSelector,omitempty"`
}

// VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution string

// VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve string

// VpcpeeringSpecInitProviderPeerVpcRefPolicy Policies for referencing.
type VpcpeeringSpecInitProviderPeerVpcRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecInitProviderPeerVpcRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecInitProviderPeerVpcRefPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecInitProviderPeerVpcRef Reference to a VPC in arubacloud to populate peerVpc.
type VpcpeeringSpecInitProviderPeerVpcRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VpcpeeringSpecInitProviderPeerVpcRefPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution string

// VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve string

// VpcpeeringSpecInitProviderPeerVpcSelectorPolicy Policies for selection.
type VpcpeeringSpecInitProviderPeerVpcSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecInitProviderPeerVpcSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecInitProviderPeerVpcSelector Selector for a VPC in arubacloud to populate peerVpc.
type VpcpeeringSpecInitProviderPeerVpcSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VpcpeeringSpecInitProviderPeerVpcSelectorPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecInitProviderProjectIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecInitProviderProjectIDRefPolicyResolution string

// VpcpeeringSpecInitProviderProjectIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecInitProviderProjectIDRefPolicyResolve string

// VpcpeeringSpecInitProviderProjectIDRefPolicy Policies for referencing.
type VpcpeeringSpecInitProviderProjectIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecInitProviderProjectIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecInitProviderProjectIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecInitProviderProjectIDRef Reference to a Project in arubacloud to populate projectId.
type VpcpeeringSpecInitProviderProjectIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VpcpeeringSpecInitProviderProjectIDRefPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution string

// VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve string

// VpcpeeringSpecInitProviderProjectIDSelectorPolicy Policies for selection.
type VpcpeeringSpecInitProviderProjectIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecInitProviderProjectIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecInitProviderProjectIDSelector Selector for a Project in arubacloud to populate projectId.
type VpcpeeringSpecInitProviderProjectIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VpcpeeringSpecInitProviderProjectIDSelectorPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecInitProviderVpcIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecInitProviderVpcIDRefPolicyResolution string

// VpcpeeringSpecInitProviderVpcIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecInitProviderVpcIDRefPolicyResolve string

// VpcpeeringSpecInitProviderVpcIDRefPolicy Policies for referencing.
type VpcpeeringSpecInitProviderVpcIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecInitProviderVpcIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecInitProviderVpcIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecInitProviderVpcIDRef Reference to a VPC in arubacloud to populate vpcId.
type VpcpeeringSpecInitProviderVpcIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VpcpeeringSpecInitProviderVpcIDRefPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution string

// VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve string

// VpcpeeringSpecInitProviderVpcIDSelectorPolicy Policies for selection.
type VpcpeeringSpecInitProviderVpcIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VpcpeeringSpecInitProviderVpcIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VpcpeeringSpecInitProviderVpcIDSelector Selector for a VPC in arubacloud to populate vpcId.
type VpcpeeringSpecInitProviderVpcIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VpcpeeringSpecInitProviderVpcIDSelectorPolicy `json:"policy,omitempty"`
}

// VpcpeeringSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type VpcpeeringSpecInitProvider struct {
	// Location Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	Name *string `json:"name,omitempty"`

	// PeerVpc (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	PeerVpc *string `json:"peerVpc,omitempty"`

	// PeerVpcRef Reference to a VPC in arubacloud to populate peerVpc.
	PeerVpcRef *VpcpeeringSpecInitProviderPeerVpcRef `json:"peerVpcRef,omitempty"`

	// PeerVpcSelector Selector for a VPC in arubacloud to populate peerVpc.
	PeerVpcSelector *VpcpeeringSpecInitProviderPeerVpcSelector `json:"peerVpcSelector,omitempty"`

	// ProjectID (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty"`

	// ProjectIDRef Reference to a Project in arubacloud to populate projectId.
	ProjectIDRef *VpcpeeringSpecInitProviderProjectIDRef `json:"projectIdRef,omitempty"`

	// ProjectIDSelector Selector for a Project in arubacloud to populate projectId.
	ProjectIDSelector *VpcpeeringSpecInitProviderProjectIDSelector `json:"projectIdSelector,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// VpcID (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	VpcID *string `json:"vpcId,omitempty"`

	// VpcIDRef Reference to a VPC in arubacloud to populate vpcId.
	VpcIDRef *VpcpeeringSpecInitProviderVpcIDRef `json:"vpcIdRef,omitempty"`

	// VpcIDSelector Selector for a VPC in arubacloud to populate vpcId.
	VpcIDSelector *VpcpeeringSpecInitProviderVpcIDSelector `json:"vpcIdSelector,omitempty"`
}

// VpcpeeringSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type VpcpeeringSpecManagementPoliciesItem string

// VpcpeeringSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type VpcpeeringSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// VpcpeeringSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type VpcpeeringSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// VpcpeeringSpec VpcpeeringSpec defines the desired state of Vpcpeering
type VpcpeeringSpec struct {
	ForProvider *VpcpeeringSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *VpcpeeringSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]VpcpeeringSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *VpcpeeringSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *VpcpeeringSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// VpcpeeringStatusAtProvider defines model for .
type VpcpeeringStatusAtProvider struct {
	// ID (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty"`

	// Location Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty"`

	// Name (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	Name *string `json:"name,omitempty"`

	// PeerVpc (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	PeerVpc *string `json:"peerVpc,omitempty"`

	// ProjectID (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty"`

	// Tags (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags *[]string `json:"tags,omitempty"`

	// Timeout resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty"`

	// URI (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty"`

	// VpcID (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	VpcID *string `json:"vpcId,omitempty"`
}

// VpcpeeringStatusConditionsItem A Condition that may apply to a resource.
type VpcpeeringStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// VpcpeeringStatus VpcpeeringStatus defines the observed state of Vpcpeering.
type VpcpeeringStatus struct {
	AtProvider *VpcpeeringStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]VpcpeeringStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Vpcpeering Vpcpeering is the Schema for the Vpcpeerings API. Manages an ArubaCloud VPC Peering connection between two VPCs, enabling private routing between them.
type Vpcpeering struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *VpcpeeringAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *VpcpeeringKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec VpcpeeringSpec defines the desired state of Vpcpeering
	Spec *VpcpeeringSpec `json:"spec,omitempty"`

	// Status VpcpeeringStatus defines the observed state of Vpcpeering.
	Status *VpcpeeringStatus `json:"status,omitempty"`
}

// IoCrossplaneArubacloudV1Alpha1VpcpeeringList VpcpeeringList is a list of Vpcpeering
type IoCrossplaneArubacloudV1Alpha1VpcpeeringList = VpcpeeringList

// VpcpeeringList VpcpeeringList is a list of Vpcpeering
type VpcpeeringList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of vpcpeerings. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneArubacloudV1Alpha1Vpcpeering `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
