// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for InputAPIVersion.
const (
	InputAPIVersionExtraResourcesFnCrossplaneIoV1Beta1 InputAPIVersion = "extra-resources.fn.crossplane.io/v1beta1"
)

// Valid indicates whether the value is a known member of the InputAPIVersion enum.
func (e InputAPIVersion) Valid() bool {
	switch e {
	case InputAPIVersionExtraResourcesFnCrossplaneIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for InputKind.
const (
	InputKindInput InputKind = "Input"
)

// Valid indicates whether the value is a known member of the InputKind enum.
func (e InputKind) Valid() bool {
	switch e {
	case InputKindInput:
		return true
	default:
		return false
	}
}

// Defines values for InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy.
const (
	InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicyOptional InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy = "Optional"
	InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicyRequired InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy = "Required"
)

// Valid indicates whether the value is a known member of the InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy enum.
func (e InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy) Valid() bool {
	switch e {
	case InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicyOptional:
		return true
	case InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicyRequired:
		return true
	default:
		return false
	}
}

// Defines values for InputSpecExtraResourcesItemSelectorMatchLabelsItemType.
const (
	InputSpecExtraResourcesItemSelectorMatchLabelsItemTypeFromCompositeFieldPath InputSpecExtraResourcesItemSelectorMatchLabelsItemType = "FromCompositeFieldPath"
	InputSpecExtraResourcesItemSelectorMatchLabelsItemTypeValue                  InputSpecExtraResourcesItemSelectorMatchLabelsItemType = "Value"
)

// Valid indicates whether the value is a known member of the InputSpecExtraResourcesItemSelectorMatchLabelsItemType enum.
func (e InputSpecExtraResourcesItemSelectorMatchLabelsItemType) Valid() bool {
	switch e {
	case InputSpecExtraResourcesItemSelectorMatchLabelsItemTypeFromCompositeFieldPath:
		return true
	case InputSpecExtraResourcesItemSelectorMatchLabelsItemTypeValue:
		return true
	default:
		return false
	}
}

// Defines values for InputSpecExtraResourcesItemType.
const (
	InputSpecExtraResourcesItemTypeReference InputSpecExtraResourcesItemType = "Reference"
	InputSpecExtraResourcesItemTypeSelector  InputSpecExtraResourcesItemType = "Selector"
)

// Valid indicates whether the value is a known member of the InputSpecExtraResourcesItemType enum.
func (e InputSpecExtraResourcesItemType) Valid() bool {
	switch e {
	case InputSpecExtraResourcesItemTypeReference:
		return true
	case InputSpecExtraResourcesItemTypeSelector:
		return true
	default:
		return false
	}
}

// Defines values for InputSpecPolicyResolution.
const (
	InputSpecPolicyResolutionOptional InputSpecPolicyResolution = "Optional"
	InputSpecPolicyResolutionRequired InputSpecPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the InputSpecPolicyResolution enum.
func (e InputSpecPolicyResolution) Valid() bool {
	switch e {
	case InputSpecPolicyResolutionOptional:
		return true
	case InputSpecPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// IoCrossplaneFnExtraResourcesV1Beta1Input Input can be used to provide input to this Function.
type IoCrossplaneFnExtraResourcesV1Beta1Input = Input

// InputAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type InputAPIVersion string

// InputKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type InputKind string

// InputSpecExtraResourcesItemRef Ref is a named reference to a single ExtraResource.
// Either Ref or Selector is required.
type InputSpecExtraResourcesItemRef struct {
	// Name The name of the object.
	Name *string `json:"name,omitempty"`
}

// InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy FromFieldPathPolicy specifies the policy for the valueFromFieldPath.
// The default is Required, meaning that an error will be returned if the
// field is not found in the composite resource.
// Optional means that if the field is not found in the composite resource,
// that label pair will just be skipped. N.B. other specified label
// matchers will still be used to retrieve the desired
// resource config, if any.
type InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy string

// InputSpecExtraResourcesItemSelectorMatchLabelsItemType Type specifies where the value for a label comes from.
type InputSpecExtraResourcesItemSelectorMatchLabelsItemType string

// InputSpecExtraResourcesItemSelectorMatchLabelsItem An ResourceSourceSelectorLabelMatcher acts like a k8s label selector but
// can draw the label value from a different path.
type InputSpecExtraResourcesItemSelectorMatchLabelsItem struct {
	// FromFieldPathPolicy FromFieldPathPolicy specifies the policy for the valueFromFieldPath.
	// The default is Required, meaning that an error will be returned if the
	// field is not found in the composite resource.
	// Optional means that if the field is not found in the composite resource,
	// that label pair will just be skipped. N.B. other specified label
	// matchers will still be used to retrieve the desired
	// resource config, if any.
	FromFieldPathPolicy *InputSpecExtraResourcesItemSelectorMatchLabelsItemFromFieldPathPolicy `json:"fromFieldPathPolicy,omitempty"`

	// Key Key of the label to match.
	Key *string `json:"key,omitempty"`

	// Type Type specifies where the value for a label comes from.
	Type *InputSpecExtraResourcesItemSelectorMatchLabelsItemType `json:"type,omitempty"`

	// Value Value specifies a literal label value.
	Value *string `json:"value,omitempty"`

	// ValueFromFieldPath ValueFromFieldPath specifies the field path to look for the label value.
	ValueFromFieldPath *string `json:"valueFromFieldPath,omitempty"`
}

// InputSpecExtraResourcesItemSelector Selector selects ExtraResource(s) via labels.
type InputSpecExtraResourcesItemSelector struct {
	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *[]InputSpecExtraResourcesItemSelectorMatchLabelsItem `json:"matchLabels,omitempty"`

	// MaxMatch MaxMatch specifies the number of extracted ExtraResources in Multiple mode, extracts all if nil.
	MaxMatch *int64 `json:"maxMatch,omitempty"`

	// MinMatch MinMatch specifies the required minimum of extracted ExtraResources in Multiple mode.
	MinMatch *int64 `json:"minMatch,omitempty"`

	// SortByFieldPath SortByFieldPath is the path to the field based on which list of ExtraResources is alphabetically sorted.
	SortByFieldPath *string `json:"sortByFieldPath,omitempty"`
}

// InputSpecExtraResourcesItemType Type specifies the way the ExtraResource is selected.
// Default is `Reference`
type InputSpecExtraResourcesItemType string

// InputSpecExtraResourcesItem ResourceSource selects a ExtraResource.
type InputSpecExtraResourcesItem struct {
	// APIVersion APIVersion is the kubernetes API Version of the target extra resource(s).
	APIVersion *string `json:"apiVersion,omitempty"`

	// Into Into is the key into which extra resources for this selector will be placed.
	Into *string `json:"into,omitempty"`

	// Kind Kind is the kubernetes kind of the target extra resource(s).
	Kind *string `json:"kind,omitempty"`

	// Namespace Namespace is the namespace in which to look for the ExtraResource.
	// If not set, the resource is assumed to be cluster-scoped.
	Namespace *string `json:"namespace,omitempty"`

	// Ref Ref is a named reference to a single ExtraResource.
	// Either Ref or Selector is required.
	Ref *InputSpecExtraResourcesItemRef `json:"ref,omitempty"`

	// Selector Selector selects ExtraResource(s) via labels.
	Selector *InputSpecExtraResourcesItemSelector `json:"selector,omitempty"`

	// Type Type specifies the way the ExtraResource is selected.
	// Default is `Reference`
	Type *InputSpecExtraResourcesItemType `json:"type,omitempty"`
}

// InputSpecPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type InputSpecPolicyResolution string

// InputSpecPolicy Policy represents the Resolution policies which apply to all
// ResourceSourceReferences in ExtraResources list.
type InputSpecPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *InputSpecPolicyResolution `json:"resolution,omitempty"`
}

// InputSpec Spec is the input to this function.
type InputSpec struct {
	// ExtraResources ExtraResources selects a list of `ExtraResource`s. The resolved
	// resources are stored in the composite resource at
	// `spec.extraResourceRefs` and is only updated if it is null.
	ExtraResources *[]InputSpecExtraResourcesItem `json:"extraResources,omitempty"`

	// Policy Policy represents the Resolution policies which apply to all
	// ResourceSourceReferences in ExtraResources list.
	Policy *InputSpecPolicy `json:"policy,omitempty"`
}

// Input Input can be used to provide input to this Function.
type Input struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *InputAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *InputKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec Spec is the input to this function.
	Spec *InputSpec `json:"spec,omitempty"`
}

// IoCrossplaneFnExtraResourcesV1Beta1InputList InputList is a list of Input
type IoCrossplaneFnExtraResourcesV1Beta1InputList = InputList

// InputList InputList is a list of Input
type InputList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of inputs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneFnExtraResourcesV1Beta1Input `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
