// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for MicroserviceAPIVersion.
const (
	MicroserviceAPIVersionPlatformExampleComV1Alpha1 MicroserviceAPIVersion = "platform.example.com/v1alpha1"
)

// Valid indicates whether the value is a known member of the MicroserviceAPIVersion enum.
func (e MicroserviceAPIVersion) Valid() bool {
	switch e {
	case MicroserviceAPIVersionPlatformExampleComV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for MicroserviceKind.
const (
	MicroserviceKindMicroservice MicroserviceKind = "Microservice"
)

// Valid indicates whether the value is a known member of the MicroserviceKind enum.
func (e MicroserviceKind) Valid() bool {
	switch e {
	case MicroserviceKindMicroservice:
		return true
	default:
		return false
	}
}

// Defines values for MicroserviceSpecCrossplaneCompositionUpdatePolicy.
const (
	MicroserviceSpecCrossplaneCompositionUpdatePolicyAutomatic MicroserviceSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	MicroserviceSpecCrossplaneCompositionUpdatePolicyManual    MicroserviceSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// Valid indicates whether the value is a known member of the MicroserviceSpecCrossplaneCompositionUpdatePolicy enum.
func (e MicroserviceSpecCrossplaneCompositionUpdatePolicy) Valid() bool {
	switch e {
	case MicroserviceSpecCrossplaneCompositionUpdatePolicyAutomatic:
		return true
	case MicroserviceSpecCrossplaneCompositionUpdatePolicyManual:
		return true
	default:
		return false
	}
}

// Defines values for MicroserviceSpecDatabaseEngine.
const (
	MicroserviceSpecDatabaseEngineMysql MicroserviceSpecDatabaseEngine = "mysql"
)

// Valid indicates whether the value is a known member of the MicroserviceSpecDatabaseEngine enum.
func (e MicroserviceSpecDatabaseEngine) Valid() bool {
	switch e {
	case MicroserviceSpecDatabaseEngineMysql:
		return true
	default:
		return false
	}
}

// ComExamplePlatformV1Alpha1Microservice Microservice provisions a VM, a managed MySQL database, and deploys a Docker image configured with database connection env vars.
type ComExamplePlatformV1Alpha1Microservice = Microservice

// MicroserviceAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type MicroserviceAPIVersion string

// MicroserviceKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type MicroserviceKind string

// MicroserviceSpecCrossplaneCompositionRef defines model for .
type MicroserviceSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// MicroserviceSpecCrossplaneCompositionRevisionRef defines model for .
type MicroserviceSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// MicroserviceSpecCrossplaneCompositionRevisionSelector defines model for .
type MicroserviceSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// MicroserviceSpecCrossplaneCompositionSelector defines model for .
type MicroserviceSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// MicroserviceSpecCrossplaneCompositionUpdatePolicy defines model for com.example.platform.v1alpha1.Microservice.spec.crossplane.compositionUpdatePolicy.
type MicroserviceSpecCrossplaneCompositionUpdatePolicy string

// MicroserviceSpecCrossplaneResourceRefsItem defines model for .
type MicroserviceSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// MicroserviceSpecCrossplane Configures how Crossplane will reconcile this composite resource
type MicroserviceSpecCrossplane struct {
	CompositionRef              *MicroserviceSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *MicroserviceSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *MicroserviceSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *MicroserviceSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *MicroserviceSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]MicroserviceSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// MicroserviceSpecDatabaseEngine Database engine. Only "mysql" is supported.
type MicroserviceSpecDatabaseEngine string

// MicroserviceSpecDatabase Database configures the managed database attached to this Microservice.
type MicroserviceSpecDatabase struct {
	// Engine Database engine. Only "mysql" is supported.
	Engine *MicroserviceSpecDatabaseEngine `json:"engine,omitempty"`
}

// MicroserviceSpecWriteConnectionSecretToRef Writes database connection details (host, port, database, username, password, endpoint) to this Secret once the Microservice is Ready.
type MicroserviceSpecWriteConnectionSecretToRef struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// MicroserviceSpec MicroserviceSpec defines the desired state of a Microservice.
type MicroserviceSpec struct {
	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *MicroserviceSpecCrossplane `json:"crossplane,omitempty"`

	// Database Database configures the managed database attached to this Microservice.
	Database *MicroserviceSpecDatabase `json:"database,omitempty"`

	// Image Docker image to deploy on the provisioned VM (e.g. adminer:4.8.1).
	Image *string `json:"image,omitempty"`

	// Port TCP port the container listens on. Used to build the status endpoint and open the security group. Defaults to 8080.
	Port *int `json:"port,omitempty"`

	// WriteConnectionSecretToRef Writes database connection details (host, port, database, username, password, endpoint) to this Secret once the Microservice is Ready.
	WriteConnectionSecretToRef *MicroserviceSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// MicroserviceStatusConditionsItem defines model for .
type MicroserviceStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// MicroserviceStatus MicroserviceStatus defines the observed state of a Microservice.
type MicroserviceStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]MicroserviceStatusConditionsItem `json:"conditions,omitempty"`

	// DatabaseHost MySQL host (public IP of the DBaaS Elastic IP).
	DatabaseHost *string `json:"databaseHost,omitempty"`

	// DatabaseName Logical database name.
	DatabaseName *string `json:"databaseName,omitempty"`

	// DatabasePort MySQL port (always 3306).
	DatabasePort *string `json:"databasePort,omitempty"`

	// DatabaseUser MySQL username.
	DatabaseUser *string `json:"databaseUser,omitempty"`

	// DeployedImage Docker image that was last successfully deployed. Used to short-circuit SSH on reconciles when nothing has changed.
	DeployedImage *string `json:"deployedImage,omitempty"`

	// Endpoint HTTP endpoint to reach the deployed application once Ready=True.
	Endpoint *string `json:"endpoint,omitempty"`

	// SubnetURI Internal — Subnet URI propagated from composed Subnet resource.
	SubnetURI *string `json:"subnetUri,omitempty"`

	// VpcURI Internal — VPC URI propagated from composed VPC resource.
	VpcURI *string `json:"vpcUri,omitempty"`
}

// Microservice Microservice provisions a VM, a managed MySQL database, and deploys a Docker image configured with database connection env vars.
type Microservice struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *MicroserviceAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *MicroserviceKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec MicroserviceSpec defines the desired state of a Microservice.
	Spec *MicroserviceSpec `json:"spec,omitempty"`

	// Status MicroserviceStatus defines the observed state of a Microservice.
	Status *MicroserviceStatus `json:"status,omitempty"`
}

// ComExamplePlatformV1Alpha1MicroserviceList MicroserviceList is a list of Microservice
type ComExamplePlatformV1Alpha1MicroserviceList = MicroserviceList

// MicroserviceList MicroserviceList is a list of Microservice
type MicroserviceList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of microservices. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]ComExamplePlatformV1Alpha1Microservice `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
