# generated by datamodel-codegen:
#   filename:  workdir/extra-resources_fn_crossplane_io_v1beta1_input.yaml

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

from ......k8s.apimachinery.pkg.apis.meta import v1


class Ref(BaseModel):
    name: str
    """
    The name of the object.
    """


class MatchLabel(BaseModel):
    fromFieldPathPolicy: Literal['Optional', 'Required'] | None = 'Required'
    """
    FromFieldPathPolicy specifies the policy for the valueFromFieldPath.
    The default is Required, meaning that an error will be returned if the
    field is not found in the composite resource.
    Optional means that if the field is not found in the composite resource,
    that label pair will just be skipped. N.B. other specified label
    matchers will still be used to retrieve the desired
    resource config, if any.
    """
    key: str
    """
    Key of the label to match.
    """
    type: Literal['FromCompositeFieldPath', 'Value'] | None = 'FromCompositeFieldPath'
    """
    Type specifies where the value for a label comes from.
    """
    value: str | None = None
    """
    Value specifies a literal label value.
    """
    valueFromFieldPath: str | None = None
    """
    ValueFromFieldPath specifies the field path to look for the label value.
    """


class Selector(BaseModel):
    matchLabels: list[MatchLabel] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    maxMatch: int | None = None
    """
    MaxMatch specifies the number of extracted ExtraResources in Multiple mode, extracts all if nil.
    """
    minMatch: int | None = None
    """
    MinMatch specifies the required minimum of extracted ExtraResources in Multiple mode.
    """
    sortByFieldPath: str | None = 'metadata.name'
    """
    SortByFieldPath is the path to the field based on which list of ExtraResources is alphabetically sorted.
    """


class ExtraResource(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion is the kubernetes API Version of the target extra resource(s).
    """
    into: str
    """
    Into is the key into which extra resources for this selector will be placed.
    """
    kind: str | None = None
    """
    Kind is the kubernetes kind of the target extra resource(s).
    """
    namespace: str | None = None
    """
    Namespace is the namespace in which to look for the ExtraResource.
    If not set, the resource is assumed to be cluster-scoped.
    """
    ref: Ref | None = None
    """
    Ref is a named reference to a single ExtraResource.
    Either Ref or Selector is required.
    """
    selector: Selector | None = None
    """
    Selector selects ExtraResource(s) via labels.
    """
    type: Literal['Reference', 'Selector'] | None = 'Reference'
    """
    Type specifies the way the ExtraResource is selected.
    Default is `Reference`
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """


class Spec(BaseModel):
    extraResources: list[ExtraResource]
    """
    ExtraResources selects a list of `ExtraResource`s. The resolved
    resources are stored in the composite resource at
    `spec.extraResourceRefs` and is only updated if it is null.
    """
    policy: Policy | None = None
    """
    Policy represents the Resolution policies which apply to all
    ResourceSourceReferences in ExtraResources list.
    """


class Input(BaseModel):
    apiVersion: Literal['extra-resources.fn.crossplane.io/v1beta1'] | None = (
        'extra-resources.fn.crossplane.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Input'] | None = 'Input'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec | None = None
    """
    Spec is the input to this function.
    """


class InputList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Input]
    """
    List of inputs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """