# generated by datamodel-codegen:
#   filename:  workdir/arubacloud_crossplane_io_v1alpha1_elasticip.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProjectIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ProjectIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    billingPeriod: str | None = None
    """
    (String) Billing cycle. Accepted values: Hour, Month, Year.
    Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
    """
    location: str | None = None
    """
    Bergamo). Changing this value forces a new resource.
    Region identifier (e.g., `ITBG-Bergamo`). Changing this value forces a new resource.
    """
    name: str | None = None
    """
    (String) Display name for the Elastic IP.
    Display name for the Elastic IP.
    """
    projectId: str | None = None
    """
    (String) ID of the project that owns this resource. Changing this value forces a new resource.
    ID of the project that owns this resource. Changing this value forces a new resource.
    """
    projectIdRef: ProjectIdRef | None = None
    """
    Reference to a Project in arubacloud to populate projectId.
    """
    projectIdSelector: ProjectIdSelector | None = None
    """
    Selector for a Project in arubacloud to populate projectId.
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags.
    List of string tags.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """


class InitProvider(BaseModel):
    billingPeriod: str | None = None
    """
    (String) Billing cycle. Accepted values: Hour, Month, Year.
    Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
    """
    location: str | None = None
    """
    Bergamo). Changing this value forces a new resource.
    Region identifier (e.g., `ITBG-Bergamo`). Changing this value forces a new resource.
    """
    name: str | None = None
    """
    (String) Display name for the Elastic IP.
    Display name for the Elastic IP.
    """
    projectId: str | None = None
    """
    (String) ID of the project that owns this resource. Changing this value forces a new resource.
    ID of the project that owns this resource. Changing this value forces a new resource.
    """
    projectIdRef: ProjectIdRef | None = None
    """
    Reference to a Project in arubacloud to populate projectId.
    """
    projectIdSelector: ProjectIdSelector | None = None
    """
    Selector for a Project in arubacloud to populate projectId.
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags.
    List of string tags.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    address: str | None = None
    """
    (String) Computed by the API. The assigned public IP address.
    Computed by the API. The assigned public IP address.
    """
    billingPeriod: str | None = None
    """
    (String) Billing cycle. Accepted values: Hour, Month, Year.
    Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
    """
    id: str | None = None
    """
    (String) Computed by the API. Unique identifier for the resource.
    """
    location: str | None = None
    """
    Bergamo). Changing this value forces a new resource.
    Region identifier (e.g., `ITBG-Bergamo`). Changing this value forces a new resource.
    """
    name: str | None = None
    """
    (String) Display name for the Elastic IP.
    Display name for the Elastic IP.
    """
    projectId: str | None = None
    """
    (String) ID of the project that owns this resource. Changing this value forces a new resource.
    ID of the project that owns this resource. Changing this value forces a new resource.
    """
    tags: list[str] | None = None
    """
    (List of String) List of string tags.
    List of string tags.
    """
    timeout: str | None = None
    """
    resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
    Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
    """
    uri: str | None = None
    """
    (String) Computed by the API. Full resource URI.
    Computed by the API. Full resource URI.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Elasticip(BaseModel):
    apiVersion: Literal['arubacloud.crossplane.io/v1alpha1'] | None = (
        'arubacloud.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Elasticip'] | None = 'Elasticip'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    ElasticipSpec defines the desired state of Elasticip
    """
    status: Status | None = None
    """
    ElasticipStatus defines the observed state of Elasticip.
    """


class ElasticipList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Elasticip]
    """
    List of elasticips. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """